DELETE FROM GameCapabilities WHERE GameCapability = 'CAPABILITY_HISTORIC_MOMENTS' ;
DELETE FROM GameCapabilities WHERE GameCapability = 'CAPABILITY_GOLDEN_AND_DARK_AGES' ;

DELETE FROM Notifications WHERE NotificationType = 'NOTIFICATION_QUEST_RECORDED' ;
DELETE FROM Notifications WHERE NotificationType = 'NOTIFICATION_COMMEMORATION_AVAILABLE' ;