INSERT OR IGNORE INTO GameModifiers (ModifierId) VALUES ('DB_BW_CITIES_ADJUST_ATTACK_RANGE') ;

INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType) VALUES ('DB_BW_CITIES_ADJUST_ATTACK_RANGE', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_BW_CITIES_ADJUST_ATTACK_RANGE', 'ModifierId', 'DB_BW_CITIES_ADJUST_ATTACK_RANGE2') ;
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES ('DB_BW_CITIES_ADJUST_ATTACK_RANGE2', 'DB_DM_CITIES_ADJUST_ATTACK_RANGE', 'DB_REQSET_IS_CITY_CENTER') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_BW_CITIES_ADJUST_ATTACK_RANGE2', 'Amount', -2) ;


INSERT OR IGNORE INTO BuildingModifiers (BuildingType, ModifierID) VALUES ('BUILDING_CASTLE', 'DB_BW_CASTLE_ADJUST_ATTACK_RANGE') ;
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES ('DB_BW_CASTLE_ADJUST_ATTACK_RANGE', 'DB_DM_CITY_ADJUST_ATTACK_RANGE', 'DB_REQSET_IS_CITY_CENTER') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_BW_CASTLE_ADJUST_ATTACK_RANGE', 'Amount', 1) ;


INSERT OR IGNORE INTO BuildingModifiers (BuildingType, ModifierID) VALUES ('BUILDING_STAR_FORT', 'DB_BW_STAR_FORT_ADJUST_ATTACKS_PER_TURN') ;
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType) VALUES ('DB_BW_STAR_FORT_ADJUST_ATTACKS_PER_TURN', 'DB_DM_CITY_ADJUST_ATTACKS_PER_TURN') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_BW_STAR_FORT_ADJUST_ATTACKS_PER_TURN', 'Amount', 1) ;

INSERT OR IGNORE INTO BuildingModifiers (BuildingType, ModifierID) VALUES ('BUILDING_STAR_FORT', 'DB_BW_STAR_FORT_ADJUST_ATTACK_RANGE') ;
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES ('DB_BW_STAR_FORT_ADJUST_ATTACK_RANGE', 'DB_DM_CITY_ADJUST_ATTACK_RANGE', 'DB_REQSET_IS_CITY_CENTER') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_BW_STAR_FORT_ADJUST_ATTACK_RANGE', 'Amount', 1) ;


INSERT OR IGNORE INTO GovernorPromotionModifiers (GovernorPromotionType, ModifierId) VALUES ('GOVERNOR_PROMOTION_EMBRASURE', 'DB_BW_EMBRASURE_RANGE') ;
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType) VALUES ('DB_BW_EMBRASURE_RANGE', 'DB_DM_CITY_DISTRICTS_ATTACH_MODIFIER') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_BW_EMBRASURE_RANGE', 'ModifierId', 'DB_BW_EMBRASURE_RANGE2') ;
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES ('DB_BW_EMBRASURE_RANGE2', 'DB_DM_CITY_ADJUST_ATTACK_RANGE', 'DB_REQSET_IS_CITY_CENTER') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_BW_EMBRASURE_RANGE2', 'Amount', 1) ;


DELETE FROM TechnologyModifiers WHERE ModifierId = 'STEEL_UNLOCK_URBAN_DEFENSES' ;

INSERT OR IGNORE INTO TechnologyModifiers (TechnologyType, ModifierId) VALUES ('TECH_STEEL', 'DB_BW_STEEL_WALLS_PRODUCTION') ;
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType) VALUES ('DB_BW_STEEL_WALLS_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_BW_STEEL_WALLS_PRODUCTION', 'BuildingType', 'BUILDING_WALLS') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_BW_STEEL_WALLS_PRODUCTION', 'Amount', 200) ;

INSERT OR IGNORE INTO TechnologyModifiers (TechnologyType, ModifierId) VALUES ('TECH_STEEL', 'DB_BW_STEEL_CASTLE_PRODUCTION') ;
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType) VALUES ('DB_BW_STEEL_CASTLE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_BW_STEEL_CASTLE_PRODUCTION', 'BuildingType', 'BUILDING_CASTLE') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_BW_STEEL_CASTLE_PRODUCTION', 'Amount', 200) ;

INSERT OR IGNORE INTO TechnologyModifiers (TechnologyType, ModifierId) VALUES ('TECH_STEEL', 'DB_BW_STEEL_STAR_FORT_PRODUCTION') ;
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType) VALUES ('DB_BW_STEEL_STAR_FORT_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_BW_STEEL_STAR_FORT_PRODUCTION', 'BuildingType', 'BUILDING_STAR_FORT') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_BW_STEEL_STAR_FORT_PRODUCTION', 'Amount', 200) ;

