DELETE FROM Building_YieldChanges WHERE BuildingType = 'BUILDING_WATER_MILL' ;
DELETE FROM BuildingModifiers WHERE BuildingType = 'BUILDING_WATER_MILL' ;

INSERT OR IGNORE INTO BuildingModifiers (BuildingType, ModifierId) VALUES ('BUILDING_WATER_MILL', 'DB_GOLD_WATER_MILL_FOOD_ON_FARM') ;
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES ('DB_GOLD_WATER_MILL_FOOD_ON_FARM', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 'DB_REQSET_HAS_FARM') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('DB_GOLD_WATER_MILL_FOOD_ON_FARM', 'Amount', 1),
('DB_GOLD_WATER_MILL_FOOD_ON_FARM', 'YieldType', 'YIELD_FOOD')
 ;
