UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_EXPERT_MARKSMAN_NAME', Description = 'LOC_DB_ABILITY_EXPERT_MARKSMAN_DESC' WHERE UnitAbilityType = 'ABILITY_EXPERT_MARKSMAN' ;

UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_RECEIVE_RANGE_BONUS_NAME', Description = 'LOC_DB_ABILITY_RECEIVE_RANGE_BONUS_DESC' WHERE UnitAbilityType = 'ABILITY_RECEIVE_RANGE_BONUS' ;

UPDATE UnitAbilities SET Name = 'LOC_ABILITY_ECONOMIC_GOLDEN_AGE_PLUNDER_IMMUNITY_NAME', Description = 'LOC_ABILITY_ECONOMIC_GOLDEN_AGE_PLUNDER_IMMUNITY_DESCRIPTION' WHERE UnitAbilityType = 'ABILITY_ECONOMIC_GOLDEN_AGE_PLUNDER_IMMUNITY' ;
UPDATE UnitAbilities SET Name = 'LOC_ABILITY_OLIGARCHY_MELEE_BUFF_NAME', Description = 'LOC_ABILITY_OLIGARCHY_MELEE_BUFF_DESCRIPTION' WHERE UnitAbilityType = 'ABILITY_OLIGARCHY_MELEE_BUFF' ;
UPDATE UnitAbilities SET Name = 'LOC_ABILITY_FASCISM_ATTACK_BUFF_NAME', Description = 'LOC_ABILITY_FASCISM_ATTACK_BUFF_DESCRIPTION' WHERE UnitAbilityType = 'ABILITY_FASCISM_ATTACK_BUFF' ;
UPDATE UnitAbilities SET Name = 'LOC_ABILITY_THEOCRACY_RELIGIOUS_BUFF_NAME', Description = 'LOC_ABILITY_THEOCRACY_RELIGIOUS_BUFF_DESCRIPTION' WHERE UnitAbilityType = 'ABILITY_THEOCRACY_RELIGIOUS_BUFF' ;

UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_TWILIGHT_VALOR_ATTACK_BONUS_NAME', Description = 'LOC_DB_ABILITY_TWILIGHT_VALOR_ATTACK_BONUS_DESC' WHERE UnitAbilityType = 'ABILITY_TWILIGHT_VALOR_ATTACK_BONUS' ;
UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_INQUISITION_FRIENDLY_TERRITORY_BONUS_NAME', Description = 'LOC_DB_ABILITY_INQUISITION_FRIENDLY_TERRITORY_BONUS_DESC' WHERE UnitAbilityType = 'ABILITY_INQUISITION_FRIENDLY_TERRITORY_BONUS' ;
UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_RECEIVE_BOMBARD_STRENGTH_BUFF_NAME', Description = 'LOC_DB_ABILITY_RECEIVE_BOMBARD_STRENGTH_BUFF_DESC' WHERE UnitAbilityType = 'ABILITY_RECEIVE_BOMBARD_STRENGTH_BUFF' ;
UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_OLIGARCHY_LEGACY_MELEE_BUFF_NAME', Description = 'LOC_DB_ABILITY_OLIGARCHY_LEGACY_MELEE_BUFF_DESC' WHERE UnitAbilityType = 'ABILITY_OLIGARCHY_LEGACY_MELEE_BUFF' ;
UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_THEOCRACY_LEGACY_RELIGIOUS_BUFF_NAME', Description = 'LOC_DB_ABILITY_THEOCRACY_LEGACY_RELIGIOUS_BUFF_DESC' WHERE UnitAbilityType = 'ABILITY_THEOCRACY_LEGACY_RELIGIOUS_BUFF' ;
UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_FASCISM_LEGACY_ATTACK_BUFF_NAME', Description = 'LOC_DB_ABILITY_FASCISM_LEGACY_ATTACK_BUFF_DESC' WHERE UnitAbilityType = 'ABILITY_FASCISM_LEGACY_ATTACK_BUFF' ;
UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_TOQUI_COMBAT_BUFF_VS_GOLDEN_AGE_NAME', Description = 'LOC_ABILITY_TOQUI_COMBAT_BUFF_VS_GOLDEN_AGE_DESCRIPTION' WHERE UnitAbilityType = 'ABILITY_TOQUI_COMBAT_BUFF_VS_GOLDEN_AGE' ;
UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_UNIT_AUTO_VETERANCY_NAME', Description = 'LOC_DB_ABILITY_UNIT_AUTO_VETERANCY_DESC' WHERE UnitAbilityType = 'ABILITY_UNIT_AUTO_VETERANCY' ;

UPDATE UnitAbilities SET Name = 'LOC_ABILITY_FINEST_HOUR_FRIENDLY_TERRITORY_NAME', Description = 'LOC_ABILITY_FINEST_HOUR_FRIENDLY_TERRITORY_DESCRIPTION' WHERE UnitAbilityType = 'ABILITY_FINEST_HOUR_FRIENDLY_TERRITORY' ;
UPDATE UnitAbilities SET Name = 'LOC_ABILITY_CYBER_WARFARE_COMBAT_BONUS_NAME', Description = 'LOC_ABILITY_CYBER_WARFARE_COMBAT_BONUS_DESCRIPTION' WHERE UnitAbilityType = 'ABILITY_CYBER_WARFARE_COMBAT_BONUS' ;
UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_DIGITAL_DEMOCRACY_DEBUFF_NAME', Description = 'LOC_DB_ABILITY_DIGITAL_DEMOCRACY_DEBUFF_DESC' WHERE UnitAbilityType = 'ABILITY_DIGITAL_DEMOCRACY_DEBUFF' ;
UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_GLOBAL_COALITION_FRIENDLY_TERRITORY_NAME', Description = 'LOC_DB_ABILITY_GLOBAL_COALITION_FRIENDLY_TERRITORY_DESC' WHERE UnitAbilityType = 'ABILITY_GLOBAL_COALITION_FRIENDLY_TERRITORY' ;

UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_AUTO_SIEGE_NAME', Description = 'LOC_ABILITY_AUTO_SIEGE_DESCRIPTION' WHERE UnitAbilityType = 'ABILITY_AUTO_SIEGE' ;
UPDATE UnitAbilities SET Name = 'LOC_DB_ABILITY_HEAL_ON_VICTORY_NAME', Description = 'LOC_DB_ABILITY_HEAL_ON_VICTORY_DESC' WHERE UnitAbilityType = 'ABILITY_HEAL_ON_VICTORY' ;
