INSERT OR REPLACE INTO CivilopediaPages
(SectionId,		PageId,			PageGroupId, PageLayoutId, Name,														SortIndex)
VALUES
('CONCEPTS',	'COMBAT_14',	'COMBAT',	'Simple',		'LOC_PEDIA_CONCEPTS_PAGE_COMBAT_14_CHAPTER_CONTENT_TITLE',	140),
('CONCEPTS',	'COMBAT_15',	'COMBAT',	'Simple',		'LOC_PEDIA_CONCEPTS_PAGE_COMBAT_15_CHAPTER_CONTENT_TITLE',	150)

;