UPDATE ModifierStrings SET Text = 'LOC_DB_PREVIEW_BARDING' WHERE ModifierId = 'TOP_COVER_DEFENSE_BONUS_VS_RANGED' AND Context = 'Preview' ;
UPDATE ModifierStrings SET Text = 'LOC_DB_PREVIEW_INTERCEPTOR' WHERE ModifierId = 'INTERCEPTOR_BONUS_VS_BOMBERS' AND Context = 'Preview' ;
UPDATE ModifierStrings SET Text = 'LOC_DB_PREVIEW_DRONE_STRENGTH' WHERE ModifierId = 'BOMBARD_STR_BUFF_FROM_DRONE' AND Context = 'Preview' ;
INSERT INTO ModifierStrings (ModifierId, Context, Text)
	SELECT 'DEFENDER_ADJUST_CITY_DEFENSE_STRENGTH', 'Preview', 'LOC_DB_PREVIEW_REDOUBT' FROM Modifiers WHERE ModifierId IN ('DEFENDER_ADJUST_CITY_DEFENSE_STRENGTH') ;
