UPDATE Buildings SET PrereqCivic = NULL, PrereqTech = 'TECH_MATHEMATICS' WHERE BuildingType = 'BUILDING_CHANCERY' ;
UPDATE ModifierArguments SET Value = Value * 2 WHERE Name = 'Amount' AND ModifierId IN (
'CONSULATE_INFLUENCEPOINTS',								-- 2 >> 4
'MINOR_CIV_SCIENTIFIC_YIELD_FOR_CONSULATE',					-- 2 >> 4
'MINOR_CIV_RELIGIOUS_YIELD_FOR_CONSULATE',					-- 2 >> 4
'MINOR_CIV_TRADE_YIELD_FOR_CONSULATE',						-- 4 >> 8
'MINOR_CIV_CULTURAL_YIELD_FOR_CONSULATE',					-- 2 >> 4
'MINOR_CIV_MILITARISTIC_PRODUCTION_FOR_CONSULATE',			-- 2 >> 4
'MINOR_CIV_INDUSTRIAL_BUILDING_PRODUCTION_FOR_CONSULATE',	-- 2 >> 4
'MINOR_CIV_INDUSTRIAL_DISTRICT_PRODUCTION_FOR_CONSULATE',	-- 2 >> 4

'CHANCERY_INFLUENCEPOINTS',									-- 3 >> 6
'CHANCERY_COUNTERYSPY_SCIENCE',								-- 3 >> 6
'MINOR_CIV_SCIENTIFIC_YIELD_FOR_CHANCERY',					-- 3 >> 6
'MINOR_CIV_RELIGIOUS_YIELD_FOR_CHANCERY',					-- 3 >> 6
'MINOR_CIV_TRADE_YIELD_FOR_CHANCERY',						-- 6 >> 12
'MINOR_CIV_CULTURAL_YIELD_FOR_CHANCERY',					-- 3 >> 6
'MINOR_CIV_MILITARISTIC_PRODUCTION_FOR_CHANCERY',			-- 3 >> 6
'MINOR_CIV_INDUSTRIAL_BUILDING_PRODUCTION_FOR_CHANCERY',	-- 3 >> 6
'MINOR_CIV_INDUSTRIAL_DISTRICT_PRODUCTION_FOR_CHANCERY'		-- 3 >> 6
) ;

INSERT INTO Types (Type, Kind) VALUES 
('DB_EXPAND_DIPLOMACY', 'KIND_PROJECT'),
('DB_EXPAND_ESPIONAGE', 'KIND_PROJECT')
;

INSERT INTO Projects 
(ProjectType,				Cost,	CostProgressionModel,				CostProgressionParam1,	PrereqDistrict,					PrereqCivic,				Name,							ShortName,								Description) VALUES 
('DB_EXPAND_DIPLOMACY',		50,		'COST_PROGRESSION_GAME_PROGRESS',	1500,					'DISTRICT_DIPLOMATIC_QUARTER',	NULL,						'LOC_NAME_DB_EXPAND_DIPLOMACY', 'LOC_SHORT_NAME_DB_EXPAND_DIPLOMACY',	'LOC_DESC_DB_EXPAND_DIPLOMACY'),
('DB_EXPAND_ESPIONAGE',		75,		'COST_PROGRESSION_GAME_PROGRESS',	1500,					'DISTRICT_DIPLOMATIC_QUARTER',	'CIVIC_DIPLOMATIC_SERVICE',	'LOC_NAME_DB_EXPAND_ESPIONAGE', 'LOC_SHORT_NAME_DB_EXPAND_ESPIONAGE',	'LOC_DESC_DB_EXPAND_ESPIONAGE')
;

INSERT INTO Modifiers (ModifierId, ModifierType) VALUES ('DB_GRANT_SPY', 'MODIFIER_PLAYER_GRANT_SPY') ;
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_GRANT_SPY', 'Amount', 1) ;

INSERT INTO ProjectCompletionModifiers (ProjectType, ModifierId) VALUES
('DB_EXPAND_DIPLOMACY',	'CIVIC_AWARD_ONE_INFLUENCE_TOKEN'),
('DB_EXPAND_ESPIONAGE',	'DB_GRANT_SPY')
;