INSERT OR REPLACE INTO LocalizedText 
(Tag, Text, Language) VALUES
('LOC_ERA_ANCIENT_DESCRIPTION', '', 'en_US'),
('LOC_ERA_CLASSICAL_DESCRIPTION', '', 'en_US'),
('LOC_ERA_MEDIEVAL_DESCRIPTION', '', 'en_US'),
('LOC_ERA_RENAISSANCE_DESCRIPTION', '', 'en_US'),
('LOC_ERA_INDUSTRIAL_DESCRIPTION', '', 'en_US'),
('LOC_ERA_MODERN_DESCRIPTION', '', 'en_US'),
('LOC_ERA_ATOMIC_DESCRIPTION', '', 'en_US'),
('LOC_ERA_INFORMATION_DESCRIPTION', '', 'en_US') ;
