DELETE FROM GreatPersonIndividualActionModifiers WHERE GreatPersonIndividualType IN (
'GREAT_PERSON_INDIVIDUAL_HILDEGARD_OF_BINGEN', 	-- Theano					ancient		shipbuilding 
'GREAT_PERSON_INDIVIDUAL_ARYABHATA', 			-- Marcus Aurelius Ammianos	ancient		construction 
'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN',			-- Archimedes				classical	apprenticeship 
'GREAT_PERSON_INDIVIDUAL_ZHANG_HENG', 			-- Ptolemy					medieval	cartography 
'GREAT_PERSON_INDIVIDUAL_EUCLID', 				-- Johannes Gutenberg		medieval	printing 
'GREAT_PERSON_INDIVIDUAL_OMAR_KHAYYAM', 		-- Richard Arkwright		renaissance	industrialization 
'GREAT_PERSON_INDIVIDUAL_DMITRI_MENDELEEV', 	-- Eli Whitney				industrial	replacable parts 
'GREAT_PERSON_INDIVIDUAL_ERWIN_SCHRODINGER', 	-- Nikola Tesla				industrial	electricity 
'GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM', 			-- Guglielmo Marconi		industrial	radio 
'GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET', 	-- Marie Curie				modern		nuclear fission 

'GREAT_PERSON_INDIVIDUAL_JAMES_YOUNG', 			--							industrial	refining 
'GREAT_PERSON_INDIVIDUAL_ALAN_TURING' 			--							modern		computers 
) ;

UPDATE GreatPersonIndividuals SET EraType = 'ERA_ANCIENT' WHERE GreatPersonIndividualType IN (
'GREAT_PERSON_INDIVIDUAL_HILDEGARD_OF_BINGEN',	-- Theano
'GREAT_PERSON_INDIVIDUAL_ARYABHATA',			-- Marcus Aurelius Ammianos
'GREAT_PERSON_INDIVIDUAL_HYPATIA'
) ;

UPDATE GreatPersonIndividuals SET EraType = 'ERA_CLASSICAL' WHERE GreatPersonIndividualType IN (
'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN'			-- Archimedes
) ;

UPDATE GreatPersonIndividuals SET EraType = 'ERA_MEDIEVAL' WHERE GreatPersonIndividualType IN (
'GREAT_PERSON_INDIVIDUAL_ZHANG_HENG',			-- Ptolemy
'GREAT_PERSON_INDIVIDUAL_EUCLID'				-- Johannes Gutenberg
) ;

UPDATE GreatPersonIndividuals SET EraType = 'ERA_RENAISSANCE' WHERE GreatPersonIndividualType IN (
'GREAT_PERSON_INDIVIDUAL_OMAR_KHAYYAM'			-- Richard Arkwright
) ;

UPDATE GreatPersonIndividuals SET EraType = 'ERA_INDUSTRIAL' WHERE GreatPersonIndividualType IN (
'GREAT_PERSON_INDIVIDUAL_DMITRI_MENDELEEV',		-- Eli Whitney
'GREAT_PERSON_INDIVIDUAL_ERWIN_SCHRODINGER',	-- Nikola Tesla
'GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM',			-- Guglielmo Marconi
'GREAT_PERSON_INDIVIDUAL_JAMES_YOUNG'
) ;

UPDATE GreatPersonIndividuals SET EraType = 'ERA_MODERN' WHERE GreatPersonIndividualType IN (
'GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET',	-- Marie Curie
'GREAT_PERSON_INDIVIDUAL_ALAN_TURING'
) ;

UPDATE GreatPersonIndividuals SET ActionRequiresCompletedDistrictType = 'DISTRICT_CAMPUS' WHERE GreatPersonIndividualType IN (
'GREAT_PERSON_INDIVIDUAL_HILDEGARD_OF_BINGEN', 	-- Theano					ancient		shipbuilding 
'GREAT_PERSON_INDIVIDUAL_ARYABHATA', 			-- Marcus Aurelius Ammianos	ancient		construction 
'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN',			-- Archimedes				classical	apprenticeship 
'GREAT_PERSON_INDIVIDUAL_ZHANG_HENG', 			-- Ptolemy					medieval	cartography 
'GREAT_PERSON_INDIVIDUAL_EUCLID', 				-- Johannes Gutenberg		medieval	printing 
'GREAT_PERSON_INDIVIDUAL_OMAR_KHAYYAM', 		-- Richard Arkwright		renaissance	industrialization 
'GREAT_PERSON_INDIVIDUAL_DMITRI_MENDELEEV', 	-- Eli Whitney				industrial	replacable parts 
'GREAT_PERSON_INDIVIDUAL_ERWIN_SCHRODINGER', 	-- Nikola Tesla				industrial	electricity 
'GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM', 			-- Guglielmo Marconi		industrial	radio 
'GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET', 	-- Marie Curie				modern		nuclear fission 

'GREAT_PERSON_INDIVIDUAL_JAMES_YOUNG', 			--							industrial	refining 
'GREAT_PERSON_INDIVIDUAL_ALAN_TURING' 			--							modern		computers 
) ;

UPDATE GreatPersonIndividuals SET ActionEffectTextOverride = NULL WHERE GreatPersonIndividualType IN (
'GREAT_PERSON_INDIVIDUAL_EUCLID',
'GREAT_PERSON_INDIVIDUAL_OMAR_KHAYYAM',
'GREAT_PERSON_INDIVIDUAL_DMITRI_MENDELEEV',
'GREAT_PERSON_INDIVIDUAL_ALAN_TURING'
) ;


INSERT INTO GreatPersonIndividualActionModifiers
(GreatPersonIndividualType,						ModifierId,								AttachmentTargetType) VALUES
('GREAT_PERSON_INDIVIDUAL_HILDEGARD_OF_BINGEN',	'DB_MOD_GRANT_TECH_SHIPBUILDING',		'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_ARYABHATA',			'DB_MOD_GRANT_TECH_CONSTRUCTION',		'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN',			'DB_MOD_GRANT_TECH_APPRENTICESHIP',		'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_ZHANG_HENG',			'DB_MOD_GRANT_TECH_CARTOGRAPHY',		'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_EUCLID',				'DB_MOD_GRANT_TECH_PRINTING',			'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_OMAR_KHAYYAM',		'DB_MOD_GRANT_TECH_INDUSTRIALIZATION',	'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_DMITRI_MENDELEEV',	'DB_MOD_GRANT_TECH_REPLACEABLE_PARTS',	'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_ERWIN_SCHRODINGER',	'DB_MOD_GRANT_TECH_ELECTRICITY',		'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM',			'DB_MOD_GRANT_TECH_RADIO',				'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET',	'DB_MOD_GRANT_TECH_NUCLEAR_FISSION',	'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),

('GREAT_PERSON_INDIVIDUAL_JAMES_YOUNG',			'DB_MOD_GRANT_TECH_REFINING',			'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_ALAN_TURING',			'DB_MOD_GRANT_TECH_COMPUTERS',			'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE')
;

UPDATE Units SET PrereqTech = 'TECH_CELESTIAL_NAVIGATION' WHERE PrereqTech = 'TECH_SHIPBUILDING' AND Combat > 0 ;	-- QUADRIREME
UPDATE Units SET PrereqTech = 'TECH_MILITARY_TACTICS' WHERE PrereqTech = 'TECH_APPRENTICESHIP' AND Combat > 0 ;		-- MAN_AT_ARMS
UPDATE Units SET PrereqTech = 'TECH_MASS_PRODUCTION' WHERE PrereqTech = 'TECH_CARTOGRAPHY' AND Combat > 0 ;			-- CARAVEL
UPDATE Units SET PrereqTech = 'TECH_STEEL' WHERE PrereqTech = 'TECH_REPLACEABLE_PARTS' AND Combat > 0 ;				-- INFANTRY
UPDATE Units SET PrereqTech = 'TECH_STEEL' WHERE PrereqTech = 'TECH_REFINING' AND Combat > 0 ;						-- BATTLESHIP
UPDATE Units SET PrereqTech = 'TECH_COMBUSTION' WHERE PrereqTech = 'TECH_ELECTRICITY' AND Combat > 0 ;				-- SUBMARINE
