UPDATE LocalizedText SET Text = 'Theano'					WHERE Tag = 'LOC_GREAT_PERSON_INDIVIDUAL_HILDEGARD_OF_BINGEN_NAME'	AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = 'Marcus Aurelius Ammianos'	WHERE Tag = 'LOC_GREAT_PERSON_INDIVIDUAL_ARYABHATA_NAME'			AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = 'Archimedes'				WHERE Tag = 'LOC_GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_NAME'			AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = 'Ptolemy'					WHERE Tag = 'LOC_GREAT_PERSON_INDIVIDUAL_ZHANG_HENG_NAME'			AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = 'Johannes Gutenberg'		WHERE Tag = 'LOC_GREAT_PERSON_INDIVIDUAL_EUCLID_NAME'				AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = 'Richard Arkwright'			WHERE Tag = 'LOC_GREAT_PERSON_INDIVIDUAL_OMAR_KHAYYAM_NAME'			AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = 'Eli Whitney'				WHERE Tag = 'LOC_GREAT_PERSON_INDIVIDUAL_DMITRI_MENDELEEV_NAME'		AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = 'Nikola Tesla'				WHERE Tag = 'LOC_GREAT_PERSON_INDIVIDUAL_ERWIN_SCHRODINGER_NAME'	AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = 'Guglielmo Marconi'			WHERE Tag = 'LOC_GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM_NAME'			AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = 'Marie Curie'				WHERE Tag = 'LOC_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_NAME'	AND Language = 'en_US' ;

UPDATE LocalizedText SET Text = '' WHERE Language = 'en_US' AND Tag IN (
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HILDEGARD_OF_BINGEN_CHAPTER_HISTORY_PARA_1',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HILDEGARD_OF_BINGEN_CHAPTER_HISTORY_PARA_2',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HILDEGARD_OF_BINGEN_CHAPTER_HISTORY_PARA_3',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ARYABHATA_CHAPTER_HISTORY_PARA_1',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ARYABHATA_CHAPTER_HISTORY_PARA_2',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ARYABHATA_CHAPTER_HISTORY_PARA_3',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ARYABHATA_CHAPTER_HISTORY_PARA_4',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_CHAPTER_HISTORY_PARA_1',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_CHAPTER_HISTORY_PARA_2',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_CHAPTER_HISTORY_PARA_3',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ZHANG_HENG_CHAPTER_HISTORY_PARA_1',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ZHANG_HENG_CHAPTER_HISTORY_PARA_2',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ZHANG_HENG_CHAPTER_HISTORY_PARA_3',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EUCLID_CHAPTER_HISTORY_PARA_1',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EUCLID_CHAPTER_HISTORY_PARA_2',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EUCLID_CHAPTER_HISTORY_PARA_3',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_OMAR_KHAYYAM_CHAPTER_HISTORY_PARA_1',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_OMAR_KHAYYAM_CHAPTER_HISTORY_PARA_2',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_OMAR_KHAYYAM_CHAPTER_HISTORY_PARA_3',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_DMITRI_MENDELEEV_CHAPTER_HISTORY_PARA_1',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_DMITRI_MENDELEEV_CHAPTER_HISTORY_PARA_2',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_DMITRI_MENDELEEV_CHAPTER_HISTORY_PARA_3',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ERWIN_SCHRODINGER_CHAPTER_HISTORY_PARA_1',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ERWIN_SCHRODINGER_CHAPTER_HISTORY_PARA_2',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ERWIN_SCHRODINGER_CHAPTER_HISTORY_PARA_3',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM_CHAPTER_HISTORY_PARA_1',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM_CHAPTER_HISTORY_PARA_2',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM_CHAPTER_HISTORY_PARA_3',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_CHAPTER_HISTORY_PARA_1',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_CHAPTER_HISTORY_PARA_2',
'LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_CHAPTER_HISTORY_PARA_3'
) ;