-- Implemented in DB_Includes_Gameplay.lua (no sql modifer attached to this ability). The ability is here just so that the units have the description on their combat panel.
INSERT OR IGNORE INTO Types (Type, Kind) VALUES 
('DB_ABILITY_GAIN_EXP_FROM_ADJACENT_BATTLES', 'KIND_ABILITY'),
('DB_ABILITY_GAIN_EXP_FROM_ADJACENT_BATTLES_SCOUTS', 'KIND_ABILITY')
;

INSERT OR IGNORE INTO UnitAbilities (UnitAbilityType, Inactive, Name, Description) VALUES 
('DB_ABILITY_GAIN_EXP_FROM_ADJACENT_BATTLES', 0, 'LOC_DB_ABILITY_GAIN_EXP_FROM_ADJACENT_BATTLES_NAME', 'LOC_DB_ABILITY_GAIN_EXP_FROM_ADJACENT_BATTLES_DESC'),
('DB_ABILITY_GAIN_EXP_FROM_ADJACENT_BATTLES_SCOUTS', 0, 'LOC_DB_ABILITY_GAIN_EXP_FROM_ADJACENT_BATTLES_SCOUTS_NAME', 'LOC_DB_ABILITY_GAIN_EXP_FROM_ADJACENT_BATTLES_SCOUTS_DESC')
;

INSERT OR IGNORE INTO TypeTags (Type, Tag) VALUES 
('DB_ABILITY_GAIN_EXP_FROM_ADJACENT_BATTLES', 'DB_CLASS_ALL_COMBAT_EXCEPT_HEROES') ;

INSERT OR IGNORE INTO TypeTags (Type, Tag)
	SELECT DISTINCT 'DB_ABILITY_GAIN_EXP_FROM_ADJACENT_BATTLES_SCOUTS', Tag FROM TypeTags WHERE Tag = 'DB_CLASS_BETTER_SCOUT' ;

