-- ('', '', 'en_US'),

INSERT OR REPLACE INTO LocalizedText 
(Tag, Text, Language) VALUES

-- original
('LOC_DB_ABILITY_EXPERT_MARKSMAN_NAME', 'Extra Attack', 'en_US'),
('LOC_DB_ABILITY_EXPERT_MARKSMAN_DESC', '+1 attack per turn.', 'en_US'),

('LOC_DB_ABILITY_RECEIVE_RANGE_BONUS_NAME', 'Airborne Observation', 'en_US'),													-- always?
('LOC_DB_ABILITY_RECEIVE_RANGE_BONUS_DESC', '{DB_POS_COLOR}+1[ENDCOLOR] [ICON_Range] when adjacent to an airborne observer (Observation Balloon, Drone, etc.) {DB_RANGE3_EXPLANATION}', 'en_US'),

('LOC_DB_ABILITY_TWILIGHT_VALOR_ATTACK_BONUS_NAME', 'Twilight Valor (Policy)', 'en_US'),
('LOC_DB_ABILITY_TWILIGHT_VALOR_ATTACK_BONUS_DESC', '{DB_POS_COLOR}+5[ICON_Strength][ENDCOLOR], but cannot heal outside home territory', 'en_US'),
('LOC_DB_ABILITY_INQUISITION_FRIENDLY_TERRITORY_BONUS_NAME', 'Inquisition (Policy)', 'en_US'),
('LOC_DB_ABILITY_INQUISITION_FRIENDLY_TERRITORY_BONUS_DESC', '+15[ICON_Religion] in home territory', 'en_US'),
('LOC_DB_ABILITY_RECEIVE_BOMBARD_STRENGTH_BUFF_NAME', 'Precision Bombardment', 'en_US'),										-- always?
('LOC_DB_ABILITY_RECEIVE_BOMBARD_STRENGTH_BUFF_DESC', '{DB_POS_COLOR}+5[ENDCOLOR][ICON_Bombard] when adjacent to a Drone', 'en_US'),
('LOC_DB_ABILITY_OLIGARCHY_LEGACY_MELEE_BUFF_NAME', 'Oligarchic Legacy', 'en_US'),
('LOC_DB_ABILITY_OLIGARCHY_LEGACY_MELEE_BUFF_DESC', '{DB_POS_COLOR}+4[ENDCOLOR][ICON_Strength]', 'en_US'),
('LOC_DB_ABILITY_THEOCRACY_LEGACY_RELIGIOUS_BUFF_NAME', 'Theocratic Legacy', 'en_US'),
('LOC_DB_ABILITY_THEOCRACY_LEGACY_RELIGIOUS_BUFF_DESC', '{DB_POS_COLOR}+5[ENDCOLOR][ICON_Religion]', 'en_US'),
('LOC_DB_ABILITY_FASCISM_LEGACY_ATTACK_BUFF_NAME', 'Fascist Legacy', 'en_US'),
('LOC_DB_ABILITY_FASCISM_LEGACY_ATTACK_BUFF_DESC', '{DB_POS_COLOR}+5[ENDCOLOR][ICON_Strength]', 'en_US'),
('LOC_DB_ABILITY_TOQUI_COMBAT_BUFF_VS_GOLDEN_AGE_NAME', 'Toqui', 'en_US'),
('LOC_DB_ABILITY_UNIT_AUTO_VETERANCY_NAME', 'Named', 'en_US'),
('LOC_DB_ABILITY_UNIT_AUTO_VETERANCY_DESC', 'Can be named immediately', 'en_US'),

('LOC_DB_ABILITY_DIGITAL_DEMOCRACY_DEBUFF_NAME', 'Digital Democracy', 'en_US'),
('LOC_DB_ABILITY_DIGITAL_DEMOCRACY_DEBUFF_DESC', '{DB_NEG_COLOR}-3[ENDCOLOR][ICON_Strength]', 'en_US'),
('LOC_DB_ABILITY_GLOBAL_COALITION_FRIENDLY_TERRITORY_NAME', 'Global Coalition', 'en_US'),
('LOC_DB_ABILITY_GLOBAL_COALITION_FRIENDLY_TERRITORY_DESC', '{DB_POS_COLOR}+7[ENDCOLOR][ICON_Strength] in home territory', 'en_US'),

('LOC_DB_ABILITY_AUTO_SIEGE_NAME', 'Auto-Siege', 'en_US'),
('LOC_DB_ABILITY_HEAL_ON_VICTORY_NAME', 'Heal on Victory', 'en_US'),
('LOC_DB_ABILITY_HEAL_ON_VICTORY_DESC', '{DB_POS_COLOR}+30?[ENDCOLOR] Health for kills', 'en_US'),


-- missing / changed for clarity
--	standard units
('LOC_ABILITY_AIR_BOMBER_ATTACK_UNIT_DEBUFF_DESCRIPTION', '{DB_NEG_COLOR}-17[ENDCOLOR][ICON_Bombard] vs units', 'en_US'),
('LOC_ABILITY_AIR_BOMBER_ATTACK_UNIT_DEBUFF_NAME', 'Bomber', 'en_US'),
('LOC_ABILITY_AIR_FIGHTER_ATTACK_DISTRICT_DEBUFF_DESCRIPTION', '{DB_NEG_COLOR}-17[ENDCOLOR][ICON_Ranged] vs cities & encampments', 'en_US'),
('LOC_ABILITY_AIR_FIGHTER_ATTACK_DISTRICT_DEBUFF_NAME', 'Fighter', 'en_US'),
('LOC_ABILITY_AIRPORT_TRAINED_AIRCRAFT_XP_NAME', 'Airport', 'en_US'),
('LOC_ABILITY_ANTI_AIR_COVER_DESCRIPTION', 'Provides air defense for adjacent tiles', 'en_US'),
('LOC_ABILITY_ANTI_AIR_COVER_NAME', 'Anti-Air Cover', 'en_US'),
('LOC_ABILITY_ANTI_CAVALRY_DESCRIPTION', '{DB_POS_COLOR}+10[ENDCOLOR][ICON_Strength] vs cavalry units', 'en_US'),
('LOC_ABILITY_ANTI_CAVALRY_NAME', 'Anti-Cavalry', 'en_US'),
('LOC_ABILITY_ANTI_SPEAR_DESCRIPTION', '{DB_POS_COLOR}+5[ENDCOLOR][ICON_STRENGTH] vs anti-cavalry units', 'en_US'),
('LOC_ABILITY_ANTI_SPEAR_NAME', 'Anti-Spear', 'en_US'),
('LOC_ABILITY_ARCHAEOLOGIST_ENTER_FOREIGN_LANDS_DESCRIPTION', 'Ignores closed borders', 'en_US'),
('LOC_ABILITY_ARCHAEOLOGIST_ENTER_FOREIGN_LANDS_NAME', 'Borderless', 'en_US'),
('LOC_ABILITY_ARMORY_TRAINED_UNIT_XP_NAME', 'Armory', 'en_US'),
('LOC_ABILITY_BARRACKS_TRAINED_UNIT_XP_NAME', 'Barracks', 'en_US'),
('LOC_ABILITY_BOMBARD_ATTACK_UNIT_DEBUFF_DESCRIPTION', '{DB_NEG_COLOR}-17[ENDCOLOR][ICON_Bombard] vs land units', 'en_US'),
('LOC_ABILITY_BOMBARD_ATTACK_UNIT_DEBUFF_NAME', 'Land Bombard Unit', 'en_US'),
('LOC_ABILITY_CHING_SHIH_PLUNDER_BONUS_NAME', 'Ching Shih', 'en_US'),
('LOC_ABILITY_CLANCY_FERNANDO_BONUS_EXPERIENCE_NAME', 'Clancy Fernando', 'en_US'),
('LOC_ABILITY_COASTAL_RAID_DESCRIPTION', 'Can capture civilian units and pillage improvements/districts adjacent to coastal waters', 'en_US'),
('LOC_ABILITY_COASTAL_RAID_NAME', 'Coastal Raid', 'en_US'),
('LOC_ABILITY_DRONE_GRANT_SIEGE_BONUS_DESCRIPTION', '{DB_POS_COLOR}+5[ENDCOLOR][ICON_Bombard] to adjacent land siege units', 'en_US'),
('LOC_ABILITY_DRONE_GRANT_SIEGE_BONUS_NAME', 'Precision Bombardment', 'en_US'),
('LOC_ABILITY_FRANCIS_DRAKE_PLUNDER_BONUS_NAME', 'Francis Drake', 'en_US'),
('LOC_ABILITY_FRIENDLY_TERRITORY_RELIGIOUS_DESCRIPTION', '{DB_POS_COLOR}+35[ENDCOLOR][ICON_Religion] in home territory', 'en_US'),
('LOC_ABILITY_FRIENDLY_TERRITORY_RELIGIOUS_NAME', 'Inquisitor', 'en_US'),
('LOC_ABILITY_GEORGY_ZHUKOV_FLANKING_BONUS_NAME', 'Georgy Zhukov', 'en_US'),
('LOC_ABILITY_GRANT_MOVEMENT_BONUS_DESCRIPTION', '{DB_POS_COLOR}+1[ENDCOLOR][ICON_Movement] to adjacent units', 'en_US'),
('LOC_ABILITY_GRANT_MOVEMENT_BONUS_NAME', 'Convoy', 'en_US'),
('LOC_ABILITY_GREAT_ADMIRAL_MOVEMENT_NAME', 'Great Admiral', 'en_US'),
('LOC_ABILITY_GREAT_GENERAL_MOVEMENT_NAME', 'Great General', 'en_US'),
('LOC_ABILITY_GREAT_LIGHTHOUSE_EMBARKED_MOVEMENT_NAME', 'Great Lighthouse', 'en_US'),
('LOC_ABILITY_GREAT_LIGHTHOUSE_MOVEMENT_NAME', 'Great Lighthouse', 'en_US'),
('LOC_ABILITY_HANGAR_TRAINED_AIRCRAFT_XP_NAME', 'Hangar', 'en_US'),
('LOC_ABILITY_HEAVY_CHARIOT_DESCRIPTION', '{DB_POS_COLOR}+1[ENDCOLOR][ICON_Movement] when starting on a flat tile', 'en_US'),
('LOC_ABILITY_HEAVY_CHARIOT_NAME', 'Wheeled', 'en_US'),
('LOC_ABILITY_HIMERIOS_BONUS_EXPERIENCE_NAME', 'Himerios', 'en_US'),
('LOC_ABILITY_HORATIO_NELSON_FLANKING_BONUS_NAME', 'Horatio Nelson', 'en_US'),
('LOC_ABILITY_IGNORE_CROSSING_RIVERS_COST_DESCRIPTION', 'Ignores river movement costs', 'en_US'),
('LOC_ABILITY_IGNORE_CROSSING_RIVERS_COST_NAME', 'Airborne Movement', 'en_US'),
('LOC_ABILITY_IGNORE_TERRAIN_COST_DESCRIPTION', 'Ignores terrain movement costs (hills, woods, rainforests, marshes, etc.)', 'en_US'),
('LOC_ABILITY_IGNORE_TERRAIN_COST_NAME', 'Airborne Movement', 'en_US'),
('LOC_ABILITY_IGNORE_ZOC_DESCRIPTION', 'Ignores zones of control', 'en_US'),
('LOC_ABILITY_IGNORE_ZOC_NAME', 'Elusive', 'en_US'),
('LOC_ABILITY_JOHN_MONASH_BONUS_EXPERIENCE_NAME', 'John Monash', 'en_US'),
('LOC_ABILITY_LASKARINA_BOUBOULINA_BONUS_EXPERIENCE_NAME', 'Laskarina Bouboulina', 'en_US'),
('LOC_ABILITY_LIGHT_CHARIOT_DESCRIPTION', '{DB_POS_COLOR}+2[ENDCOLOR][ICON_Movement] when starting on a flat tile', 'en_US'),
('LOC_ABILITY_LIGHT_CHARIOT_NAME', 'Wheeled', 'en_US'),
('LOC_ABILITY_LIGHTHOUSE_TRAINED_UNIT_XP_NAME', 'Lighthouse', 'en_US'),
('LOC_ABILITY_MEDIC_HEAL_DESCRIPTION', '{DB_POS_COLOR}+20[ENDCOLOR] healing to adjacent units', 'en_US'),
('LOC_ABILITY_MEDIC_HEAL_NAME', 'Medic', 'en_US'),
('LOC_ABILITY_MILITARY_ACADEMY_TRAINED_UNIT_XP_NAME', 'Military Academy', 'en_US'),
('LOC_ABILITY_NIHANG_ACADEMY_STRENGTH_NAME', 'Nihang: Military Academy', 'en_US'),
('LOC_ABILITY_NIHANG_ARMORY_STRENGTH_NAME', 'Nihang: Armory', 'en_US'),
('LOC_ABILITY_NIHANG_BARRACKS_STRENGTH_NAME', 'Nihang: Barracks', 'en_US'),
('LOC_ABILITY_NO_FOREIGN_SPREAD_DESCRIPTION', 'Cannot spread to foreign cities', 'en_US'),
('LOC_ABILITY_NO_FOREIGN_SPREAD_NAME', 'Inquisitor', 'en_US'),
('LOC_ABILITY_NO_MOVE_AND_SHOOT_DESCRIPTION', 'Cannot attack after moving', 'en_US'),
('LOC_ABILITY_NO_MOVE_AND_SHOOT_NAME', 'Setup Required', 'en_US'),
('LOC_ABILITY_OBSERVATION_STRENGTH_BONUS_DESCRIPTION', '{DB_POS_COLOR}+1[ENDCOLOR][ICON_Range] for adjacent siege units {DB_RANGE3_EXPLANATION}', 'en_US'),
('LOC_ABILITY_OBSERVATION_STRENGTH_BONUS_NAME', 'Airborne Observation', 'en_US'),
('LOC_ABILITY_PARADROP_DESCRIPTION', 'Can paradrop', 'en_US'),
('LOC_ABILITY_PARADROP_NAME', 'Paratrooper', 'en_US'),
('LOC_ABILITY_RAJENDRA_CHOLA_PLUNDER_BONUS_NAME', 'Rajendra Chola', 'en_US'),
('LOC_ABILITY_RANGED_ATTACK_DISTRICT_DEBUFF_DESCRIPTION', '{DB_NEG_COLOR}-17[ENDCOLOR][ICON_Ranged] vs cities, encampments, & naval units', 'en_US'),
('LOC_ABILITY_RANGED_ATTACK_DISTRICT_DEBUFF_NAME', 'Ranged Land Unit', 'en_US'),
('LOC_ABILITY_RELIGIOUS_CANNOT_ATTACK_DESCRIPTION', 'Cannot attack', 'en_US'),
('LOC_ABILITY_RELIGIOUS_CANNOT_ATTACK_NAME', 'Peaceful', 'en_US'),
('LOC_ABILITY_RELIGIOUS_ENTER_FOREIGN_LANDS_DESCRIPTION', 'Ignores closed borders', 'en_US'),
('LOC_ABILITY_RELIGIOUS_ENTER_FOREIGN_LANDS_NAME', 'Borderless', 'en_US'),
('LOC_ABILITY_ROCK_BAND_ENTER_FOREIGN_LANDS_DESCRIPTION', 'Ignores closed borders', 'en_US'),
('LOC_ABILITY_ROCK_BAND_ENTER_FOREIGN_LANDS_NAME', 'Borderless', 'en_US'),
('LOC_ABILITY_SEAPORT_TRAINED_UNIT_XP_NAME', 'Seaport', 'en_US'),
('LOC_ABILITY_SEE_HIDDEN_DESCRIPTION', 'Reveals stealth units within sight range', 'en_US'),
('LOC_ABILITY_SEE_HIDDEN_NAME', 'Spotter', 'en_US'),
('LOC_ABILITY_SERGEY_GORSHKOV_BONUS_EXPERIENCE_NAME', 'Sergey Gorshkov', 'en_US'),
('LOC_ABILITY_SHIPYARD_TRAINED_UNIT_XP_NAME', 'Shipyard', 'en_US'),
('LOC_ABILITY_STABLE_TRAINED_UNIT_XP_NAME', 'Stable', 'en_US'),
('LOC_ABILITY_STEALTH_DESCRIPTION', 'Remains hidden from units more than 1 tile away', 'en_US'),
('LOC_ABILITY_STEALTH_NAME', 'Stealth', 'en_US'),
('LOC_ABILITY_TIMUR_BONUS_EXPERIENCE_NAME', 'Timur', 'en_US'),
('LOC_ABILITY_TRADE_ROUTE_PLUNDER_IMMUNITY_SEA_DESCRIPTION', 'While on water, [ICON_TradeRoute] Trade Route cannot be plundered. (Suzerain of {LOC_CIVILIZATION_LISBON_NAME})', 'en_US'),
('LOC_ABILITY_UNIT_FIGHT_WHILE_EMBARKED_DESCRIPTION', 'Can attack while embarked', 'en_US'),
('LOC_ABILITY_UNIT_FIGHT_WHILE_EMBARKED_NAME', 'Embarked Combat', 'en_US'),
('LOC_ABILITY_UNIT_WMD_RESISTANCE_DESCRIPTION', 'Resistant to WMDs', 'en_US'),
('LOC_ABILITY_UNIT_WMD_RESISTANCE_NAME', 'Nuke-Proof', 'en_US'),
('LOC_ABILITY_UNOBSTRUCTED_VIEW_DESCRIPTION', 'Sight ignores terrain (mountains, hills, woods, rainforests, etc.)', 'en_US'),
('LOC_ABILITY_UNOBSTRUCTED_VIEW_NAME', 'Unobstructed View', 'en_US'),
('LOC_ABILITY_VIJAYA_WIMALARATNE_BONUS_EXPERIENCE_NAME', 'Vijaya Wimalaratne', 'en_US'),
('LOC_ABILITY_WOLIN_LAND_UNITS_NAME', 'Wolin', 'en_US'),
('LOC_ABILITY_WOLIN_NAVAL_UNITS_NAME', 'Wolin', 'en_US'),
('LOC_ABILITY_WOLIN_NAVAL_UNITS_UNITS_NAME', 'Wolin', 'en_US'),





-- missing / changed for clarity
--	unique units
('LOC_ABILITY_BARBAROSSA_COMBAT_BONUS_VS_CITY_STATES_NAME', 'Barbarossa', 'en_US'),
('LOC_ABILITY_BASILIKOI_TRAINED_UNIT_XP_NAME', 'Basilikoi', 'en_US'),
-- ('LOC_ABILITY_BERSERKER_MOVEMENT_DESCRIPTION', '+2[ICON_Movement] when starting in enemy territory', 'en_US'),
-- ('LOC_ABILITY_BERSERKER_MOVEMENT_NAME', '+2[ICON_Movement] when starting in enemy territory', 'en_US'),
-- ('LOC_ABILITY_BERSERKER_RAGE_DESCRIPTION', '+10[ICON_Strength] attack[NEWLINE][ICON_Bullet]-5[ICON_Strength] defense', 'en_US'),
-- ('LOC_ABILITY_BERSERKER_RAGE_NAME', '+10[ICON_Strength] attack[NEWLINE][ICON_Bullet]-5[ICON_Strength] defense', 'en_US'),
-- ('LOC_ABILITY_BIREME_PROTECT_TRADER_DESCRIPTION', 'Protects nearby naval traders from being plundered', 'en_US'),
-- ('LOC_ABILITY_BIREME_PROTECT_TRADER_NAME', 'Protects nearby naval traders from being plundered', 'en_US'),
-- ('LOC_ABILITY_BLACK_ARMY_DESCRIPTION', '+3[ICON_Strength] per adjacent levied unit', 'en_US'),
-- ('LOC_ABILITY_BLACK_ARMY_NAME', '+3[ICON_Strength] per adjacent levied unit', 'en_US'),
-- ('LOC_ABILITY_CAPTIVE_WORKERS_DESCRIPTION', 'Can capture builders from defeated military units', 'en_US'),
-- ('LOC_ABILITY_CAPTIVE_WORKERS_NAME', 'Can capture builders from defeated military units', 'en_US'),
-- ('LOC_ABILITY_CAROLEAN_DESCRIPTION', '+3[ICON_Strength] per unused [ICON_Movement]', 'en_US'),
-- ('LOC_ABILITY_CAROLEAN_NAME', '+3[ICON_Strength] per unused [ICON_Movement]', 'en_US'),
-- ('LOC_ABILITY_CONQUISTADOR_DESCRIPTION', '+10[ICON_Strength] when next to a religious unit[NEWLINE][ICON_Bullet]Converts cities to religion on capture', 'en_US'),
-- ('LOC_ABILITY_CONQUISTADOR_NAME', '+10[ICON_Strength] when next to a religious unit[NEWLINE][ICON_Bullet]Converts cities to religion on capture', 'en_US'),
-- ('LOC_ABILITY_CORBACI_DESCRIPTION', 'Free promotion', 'en_US'),
-- ('LOC_ABILITY_CORBACI_NAME', 'Free promotion', 'en_US'),
-- ('LOC_ABILITY_CORSAIR_DESCRIPTION', 'Coastal raids don''t cost any movement', 'en_US'),
-- ('LOC_ABILITY_CORSAIR_NAME', 'Coastal raids don''t cost any movement', 'en_US'),
-- ('LOC_ABILITY_COSSACK_DESCRIPTION', 'Can move after attacking[NEWLINE][ICON_Bullet]+5[ICON_Strength] in or adjacent to home territory', 'en_US'),
-- ('LOC_ABILITY_COSSACK_NAME', 'Can move after attacking[NEWLINE][ICON_Bullet]+5[ICON_Strength] in or adjacent to home territory', 'en_US'),
-- ('LOC_ABILITY_CREE_OKIHTCITAW_DESCRIPTION', 'Free promotion', 'en_US'),
('LOC_ABILITY_CREE_OKIHTCITAW_NAME', 'Okihtcitaw', 'en_US'),
-- ('LOC_ABILITY_DIGGER_DESCRIPTION', '+10[ICON_Strength] on coastal tiles[NEWLINE][ICON_Bullet]+5[ICON_Strength] outside home territory', 'en_US'),
-- ('LOC_ABILITY_DIGGER_NAME', '+10[ICON_Strength] on coastal tiles[NEWLINE][ICON_Bullet]+5[ICON_Strength] outside home territory', 'en_US'),
-- ('LOC_ABILITY_DROMON_DESCRIPTION', '+10[ICON_Strength] vs units', 'en_US'),
-- ('LOC_ABILITY_DROMON_NAME', '+10[ICON_Strength] vs units', 'en_US'),
-- ('LOC_ABILITY_DUTCH_ZEVEN_PROVINCIEN_DESCRIPTION', '+7[ICON_Strength] vs cities & encampments', 'en_US'),
('LOC_ABILITY_DUTCH_ZEVEN_PROVINCIEN_NAME', 'De Zeven Provincien', 'en_US'),
-- ('LOC_ABILITY_ETHIOPIAN_OROMO_CAVALRY_DESCRIPTION', 'No hill movement costs', 'en_US'),
-- ('LOC_ABILITY_ETHIOPIAN_OROMO_CAVALRY_NAME', 'No hill movement costs', 'en_US'),
-- ('LOC_ABILITY_GAESATAE_DESCRIPTION', '+10[ICON_Strength] vs units with higher base combat strength[NEWLINE][ICON_Bullet]+5[ICON_Strength] vs cities & encampments', 'en_US'),
-- ('LOC_ABILITY_GAESATAE_NAME', '+10[ICON_Strength] vs units with higher base combat strength[NEWLINE][ICON_Bullet]+5[ICON_Strength] vs cities & encampments', 'en_US'),
-- ('LOC_ABILITY_GARDE_DESCRIPTION', '+10[ICON_Strength] on home continent[NEWLINE][ICON_Bullet]+10[ICON_GreatGeneral] Great General points for kills', 'en_US'),
-- ('LOC_ABILITY_GARDE_NAME', '+10[ICON_Strength] on home continent[NEWLINE][ICON_Bullet]+10[ICON_GreatGeneral] Great General points for kills', 'en_US'),
-- ('LOC_ABILITY_GEORGIAN_KHEVSURETI_DESCRIPTION', '+7[ICON_Strength] on hills', 'en_US'),
('LOC_ABILITY_GEORGIAN_KHEVSURETI_NAME', 'Khevsureti', 'en_US'),
('LOC_ABILITY_GORGO_POLICY_SLOT_COMBAT_BONUS_NAME', 'Gorgo', 'en_US'),
-- ('LOC_ABILITY_HETAIROI_DESCRIPTION', '+5[ICON_Strength] next to a Great General[NEWLINE][ICON_Bullet]+5[ICON_GreatGeneral] Great General points for kills', 'en_US'),
('LOC_ABILITY_HETAIROI_NAME', 'Hetairoi', 'en_US'),
-- ('LOC_ABILITY_HOPLITE_DESCRIPTION', '+10[ICON_Strength] when next to another Hoplite', 'en_US'),
-- ('LOC_ABILITY_HOPLITE_NAME', '+10[ICON_Strength] when next to another Hoplite', 'en_US'),
-- ('LOC_ABILITY_HULCHE_DESCRIPTION', '+5[ICON_Strength] vs damaged units', 'en_US'),
('LOC_ABILITY_HULCHE_NAME', 'Hulche', 'en_US'),
-- ('LOC_ABILITY_HUSZAR_DESCRIPTION', '+3[ICON_STRENGTH] per alliance', 'en_US'),
-- ('LOC_ABILITY_HUSZAR_NAME', '+3[ICON_STRENGTH] per alliance', 'en_US'),
-- ('LOC_ABILITY_HYPASPIST_DESCRIPTION', '+5[ICON_Strength] vs cities & encampments[NEWLINE][ICON_Bullet]+50% support', 'en_US'),
('LOC_ABILITY_HYPASPIST_NAME', 'Hypaspist', 'en_US'),
-- ('LOC_ABILITY_JONG_DESCRIPTION', '+5[ICON_Strength] when in an escort formation[NEWLINE][ICON_Bullet]Movement applies to units in an escort formation', 'en_US'),
('LOC_ABILITY_JONG_NAME', 'Jong', 'en_US'),
-- ('LOC_ABILITY_LLANERO_ADJACENCY_STRENGTH_DESCRIPTION', '+2[ICON_Strength] from each adjacent Llanero', 'en_US'),
('LOC_ABILITY_LLANERO_ADJACENCY_STRENGTH_NAME', 'Llanero', 'en_US'),
-- ('LOC_ABILITY_LONGSHIP_MOVEMENT_DESCRIPTION', '+1[ICON_Movement] on coastal tiles', 'en_US'),
-- ('LOC_ABILITY_LONGSHIP_MOVEMENT_NAME', '+1[ICON_Movement] on coastal tiles', 'en_US'),
-- ('LOC_ABILITY_MAMLUK_DESCRIPTION', 'Heals after movement and combat', 'en_US'),
-- ('LOC_ABILITY_MAMLUK_NAME', 'Heals after movement and combat', 'en_US'),
('LOC_ABILITY_MANA_NAME', 'Mana', 'en_US'),
-- ('LOC_ABILITY_MANDEKALU_DESCRIPTION', 'Protects nearby land traders from beings plundered[NEWLINE][ICON_Bullet]+[ICON_GOLD] For Kills', 'en_US'),
-- ('LOC_ABILITY_MANDEKALU_NAME', 'Protects nearby land traders from beings plundered[NEWLINE][ICON_Bullet]+[ICON_GOLD] For Kills', 'en_US'),
-- ('LOC_ABILITY_MAPUCHE_MALON_RAIDER_DESCRIPTION', '+5[ICON_Strength] within 4 tiles home territory[NEWLINE][ICON_Bullet]Pillaging costs 1 [ICON_Movement]', 'en_US'),
('LOC_ABILITY_MAPUCHE_MALON_RAIDER_NAME', 'Malon Raider', 'en_US'),
-- ('LOC_ABILITY_MONGOLIAN_KESHIG_DESCRIPTION', 'Movement applies to units in an escort formation', 'en_US'),
('LOC_ABILITY_MONGOLIAN_KESHIG_NAME', 'Keshig', 'en_US'),
-- ('LOC_ABILITY_MOUNTIE_DESCRIPTION', 'Can create a national park[NEWLINE][ICON_Bullet]+5[ICON_Strength] within 2 tiles of a national park', 'en_US'),
-- ('LOC_ABILITY_MOUNTIE_NAME', 'Can create a national park[NEWLINE][ICON_Bullet]+5[ICON_Strength] within 2 tiles of a national park', 'en_US'),
-- ('LOC_ABILITY_MUSTANG_DESCRIPTION', '+5[ICON_Strength] vs fighters[NEWLINE][ICON_Bullet]+50% xp', 'en_US'),
-- ('LOC_ABILITY_MUSTANG_NAME', '+5[ICON_Strength] vs fighters[NEWLINE][ICON_Bullet]+50% xp', 'en_US'),
-- ('LOC_ABILITY_NAGAO_DESCRIPTION', '+10[ICON_Strength] defense vs ranged units[NEWLINE][ICON_Bullet]Can see through woods/rainforests[NEWLINE][ICON_Bullet]No woods/rainforest movement costs', 'en_US'),
-- ('LOC_ABILITY_NAGAO_NAME', '+10[ICON_Strength] defense vs ranged units[NEWLINE][ICON_Bullet]Can see through woods/rainforests[NEWLINE][ICON_Bullet]No woods/rainforest movement costs', 'en_US'),
-- ('LOC_ABILITY_NAU_DESCRIPTION', 'Free Promotion', 'en_US'),
-- ('LOC_ABILITY_NAU_NAME', 'Free Promotion', 'en_US'),
('LOC_ABILITY_PHILIP_II_COMBAT_BONUS_OTHER_RELIGION_NAME', 'Philip II', 'en_US'),
-- ('LOC_ABILITY_PRIZE_SHIPS_DESCRIPTION', 'Can capture defeated naval units', 'en_US'),
-- ('LOC_ABILITY_PRIZE_SHIPS_NAME', 'Can capture defeated naval units', 'en_US'),
('LOC_ABILITY_PUSHBACK', 'Impel', 'en_US'),
-- ('LOC_ABILITY_PUSHBACK_DESCRIPTION', 'Pushes back defending units', 'en_US'),
-- ('LOC_ABILITY_REDCOAT_DESCRIPTION', '+10[ICON_Strength] on foreign continents', 'en_US'),
-- ('LOC_ABILITY_REDCOAT_NAME', '+10[ICON_Strength] on foreign continents', 'en_US'),
-- ('LOC_ABILITY_ROMAN_LEGION_BUILD_DESCRIPTION', 'Can build a Roman fort', 'en_US'),
('LOC_ABILITY_ROMAN_LEGION_BUILD_NAME', 'Legion', 'en_US'),
-- ('LOC_ABILITY_ROUGH_RIDER_DESCRIPTION', '+10[ICON_Strength] on hills[NEWLINE][ICON_Bullet]+[ICON_Culture] for kills on home continent', 'en_US'),
-- ('LOC_ABILITY_ROUGH_RIDER_NAME', '+10[ICON_Strength] on hills[NEWLINE][ICON_Bullet]+[ICON_Culture] for kills on home continent', 'en_US'),
-- ('LOC_ABILITY_SABUM_KIBITTUM_ANTI_CAVALRY_DESCRIPTION', '+17[ICON_Strength] vs cavalry', 'en_US'),
-- ('LOC_ABILITY_SABUM_KIBITTUM_ANTI_CAVALRY_NAME', '+17[ICON_Strength] vs cavalry', 'en_US'),
-- ('LOC_ABILITY_SAMURAI_DESCRIPTION', 'No [ICON_Strength] loss for being damaged', 'en_US'),
-- ('LOC_ABILITY_SAMURAI_NAME', 'No [ICON_Strength] loss for being damaged', 'en_US'),
-- ('LOC_ABILITY_SCOTTISH_HIGHLANDER_DESCRIPTION', '+5[ICON_Strength] on hills and in woods', 'en_US'),
('LOC_ABILITY_SCOTTISH_HIGHLANDER_NAME', 'Highlander', 'en_US'),
-- ('LOC_ABILITY_TAGMA_DESCRIPTION', 'Nearby land units get +4[ICON_Strength] or +4[ICON_RELIGION]', 'en_US'),
-- ('LOC_ABILITY_TAGMA_NAME', 'Nearby land units get +4[ICON_Strength] or +4[ICON_RELIGION]', 'en_US'),
-- ('LOC_ABILITY_TAGMA_NONRELIGIOUS_COMBAT_DESCRIPTION', '+4[ICON_Strength] from nearby Tagma', 'en_US'),
-- ('LOC_ABILITY_TAGMA_NONRELIGIOUS_COMBAT_NAME', '+4[ICON_Strength] from nearby Tagma', 'en_US'),
-- ('LOC_ABILITY_TAGMA_RELIGIOUS_COMBAT_DESCRIPTION', '+4[ICON_RELIGION] from nearby Tagma', 'en_US'),
-- ('LOC_ABILITY_TAGMA_RELIGIOUS_COMBAT_DESCRIPTION', '+4[ICON_RELIGION] from nearby Tagma', 'en_US'),
-- ('LOC_ABILITY_TOA_DESCRIPTION', '-5[ICON_STRENGTH] to adjacent enemy units[NEWLINE][ICON_Bullet]Can build a Pa', 'en_US'),
('LOC_ABILITY_TOA_NAME', 'Toa', 'en_US'),
-- ('LOC_ABILITY_UBOAT_DESCRIPTION', '+10[ICON_Strength] on ocean tiles', 'en_US'),
-- ('LOC_ABILITY_UBOAT_NAME', '+10[ICON_Strength] on ocean tiles', 'en_US'),
-- ('LOC_ABILITY_VARU_DESCRIPTION', '-5[ICON_STRENGTH] to adjacent enemy units', 'en_US'),
-- ('LOC_ABILITY_VARU_NAME', '-5[ICON_STRENGTH] to adjacent enemy units', 'en_US'),
-- ('LOC_ABILITY_VOI_CHIEN_DESCRIPTION', 'Can move after attacking', 'en_US'),
-- ('LOC_ABILITY_VOI_CHIEN_NAME', 'Can move after attacking', 'en_US'),
-- ('LOC_ABILITY_ZULU_IMPI_DESCRIPTION', '+100% flanking[NEWLINE][ICON_Bullet]+25% xp', 'en_US'),
('LOC_ABILITY_ZULU_IMPI_NAME', 'Impi', 'en_US'),


('', '', 'en_US') ;