INSERT INTO GreatWork_ValidSubTypes (GreatWorkSlotType, GreatWorkObjectType) VALUES ('GREATWORKSLOT_CATHEDRAL', 'GREATWORKOBJECT_RELIC') ;
INSERT INTO GreatWork_ValidSubTypes (GreatWorkSlotType, GreatWorkObjectType) VALUES ('GREATWORKSLOT_CATHEDRAL', 'GREATWORKOBJECT_MUSIC') ;
