UPDATE Technologies SET Description = 'LOC_DB_TECH_SIEGE_TACTICS_DESC' WHERE TechnologyType = 'TECH_SIEGE_TACTICS' ;

INSERT OR IGNORE INTO TechnologyModifiers (TechnologyType, ModifierId) VALUES ('TECH_SIEGE_TACTICS', 'DB_SIEGE_TACTICS_GRANT_SAPPER_ABILITY_TO_ENGINEERS') ;
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType) VALUES ('DB_SIEGE_TACTICS_GRANT_SAPPER_ABILITY_TO_ENGINEERS', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY') ;
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_SIEGE_TACTICS_GRANT_SAPPER_ABILITY_TO_ENGINEERS', 'AbilityType', 'DB_ABILITY_SAPPER') ;

INSERT OR REPLACE INTO Types 
(Type,												Kind) VALUES 
('DB_ABILITY_SAPPER',								'KIND_ABILITY'),
('DB_ABILITY_BATTERING_RAM_IMPOTENT_TO_CASTLE',		'KIND_ABILITY')
;

INSERT OR REPLACE INTO TypeTags 
(Type,												Tag) VALUES 
('DB_ABILITY_SAPPER',								'DB_CLASS_UNIT_MILITARY_ENGINEER'),
('DB_ABILITY_BATTERING_RAM_IMPOTENT_TO_CASTLE',		'DB_CLASS_UNIT_BATTERING_RAM')
;

INSERT OR REPLACE INTO UnitAbilities 
(UnitAbilityType,									Name,														Description,												Inactive) VALUES 
('DB_ABILITY_SAPPER',								'LOC_NAME_DB_ABILITY_SAPPER',								'LOC_DESC_DB_ABILITY_SAPPER',								1),
('DB_ABILITY_BATTERING_RAM_IMPOTENT_TO_CASTLE',		'LOC_NAME_DB_ABILITY_BATTERING_RAM_IMPOTENT_TO_CASTLE',		'LOC_DESC_DB_ABILITY_BATTERING_RAM_IMPOTENT_TO_CASTLE',		0)
;

INSERT INTO UnitAbilityModifiers 
(UnitAbilityType,									ModifierId) VALUES
('DB_ABILITY_SAPPER',								'DB_MOD_SAPPER_MELEE'),
('DB_ABILITY_SAPPER',								'DB_MOD_SAPPER_ANTICAV'),
('DB_ABILITY_BATTERING_RAM_IMPOTENT_TO_CASTLE',		'DB_MOD_ADJACENT_CASTLE_PREVENTS_RAM')
;

INSERT INTO Modifiers 
(ModifierId,								ModifierType,														SubjectRequirementSetId) VALUES
('DB_MOD_SAPPER_MELEE',						'DB_DM_CAN_WALL_ATTACK_PROMOTION_CLASS',							NULL),
('DB_MOD_SAPPER_ANTICAV',					'DB_DM_CAN_WALL_ATTACK_PROMOTION_CLASS',							NULL),
('DB_MOD_ADJACENT_CASTLE_PREVENTS_RAM',		'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER',								'DB_REQSET_INSIDE_FOREIGN_TERRITORY'),
('DB_MOD_ADJACENT_CASTLE_PREVENTS_RAM2',	'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER',								'DB_REQSET_NEXT_TO_CITY_OR_ENCAMPMENT'),
('DB_MOD_ADJACENT_CASTLE_PREVENTS_RAM3',	'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',								'DB_REQSET_ADJACENT_UNIT_AT_WAR'),
('DB_MOD_ADJACENT_CASTLE_PREVENTS_RAM4',	'MODIFIER_SINGLE_CITY_ADJUST_PREVENT_MELEE_ATTACK_OUTER_DEFENSES',	'DB_REQSET_CITY_HAS_CASTLE')
;

INSERT INTO ModifierArguments
(ModifierId,								Name,				Value) VALUES
('DB_MOD_SAPPER_MELEE',						'PromotionClass',	'PROMOTION_CLASS_MELEE'),
('DB_MOD_SAPPER_ANTICAV',					'PromotionClass',	'PROMOTION_CLASS_ANTI_CAVALRY'),
('DB_MOD_ADJACENT_CASTLE_PREVENTS_RAM',		'ModifierId',		'DB_MOD_ADJACENT_CASTLE_PREVENTS_RAM2'),
('DB_MOD_ADJACENT_CASTLE_PREVENTS_RAM2',	'ModifierId',		'DB_MOD_ADJACENT_CASTLE_PREVENTS_RAM3'),
('DB_MOD_ADJACENT_CASTLE_PREVENTS_RAM3',	'ModifierId',		'DB_MOD_ADJACENT_CASTLE_PREVENTS_RAM4')
;

DELETE FROM Modifiers WHERE ModifierId IN ('CASTLE_PREVENT_MELEE_ATTACK_OUTER_DEFENSES', 'STAR_FORT_PREVENT_MELEE_ATTACK_OUTER_DEFENSES') ;