DELETE FROM GameCapabilities WHERE GameCapability = 'CAPABILITY_DISPLAY_HUD_WORLD_RANKINGS' ;
DELETE FROM GameCapabilities WHERE GameCapability = 'CAPABILITY_LENS_GOVERNMENT' ;
DELETE FROM Notifications WHERE NotificationType = 'NOTIFICATION_WONDER_COMPLETED' ;