-- Fighter
INSERT INTO UnitPromotionPrereqs ('UnitPromotion', 'PrereqUnitPromotion') VALUES
('PROMOTION_INTERCEPTOR', 'PROMOTION_COCKPIT_ARMOR'),
('PROMOTION_STRAFE', 'PROMOTION_DOGFIGHTING'),
('PROMOTION_GROUND_CREWS', 'PROMOTION_STRAFE'),
('PROMOTION_TANK_BUSTER', 'PROMOTION_INTERCEPTOR')
;