-- Naval Raider
DELETE FROM UnitPromotionPrereqs WHERE UnitPromotion IN 
	(SELECT UnitPromotionType FROM UnitPromotions WHERE PromotionClass = 'PROMOTION_CLASS_NAVAL_RAIDER') ;

INSERT INTO UnitPromotionPrereqs (UnitPromotion, PrereqUnitPromotion) VALUES
('PROMOTION_SWIFT_KEEL', 'PROMOTION_LOOT'),
('PROMOTION_SWIFT_KEEL', 'PROMOTION_BOARDING'),
('PROMOTION_HOMING_TORPEDOES', 'PROMOTION_LOOT'),
('PROMOTION_HOMING_TORPEDOES', 'PROMOTION_BOARDING'),
('PROMOTION_OBSERVATION', 'PROMOTION_SWIFT_KEEL'),
('PROMOTION_OBSERVATION', 'PROMOTION_HOMING_TORPEDOES'),
('PROMOTION_SILENT_RUNNING', 'PROMOTION_SWIFT_KEEL'),
('PROMOTION_SILENT_RUNNING', 'PROMOTION_HOMING_TORPEDOES'),
('PROMOTION_WOLFPACK', 'PROMOTION_OBSERVATION'),
('PROMOTION_WOLFPACK', 'PROMOTION_SILENT_RUNNING')
;

UPDATE Units SET BaseMoves = BaseMoves + 1 WHERE UnitType = 'UNIT_SUBMARINE' ;

INSERT INTO Types (Type, Kind) VALUES 
('DB_ABILITY_LESS_EFFECTIVE_VS_LAND_UNITS', 'KIND_ABILITY'),
('DB_ABILITY_LESS_EFFECTIVE_VS_WALLS', 'KIND_ABILITY')
;

INSERT INTO TypeTags (Type, Tag) VALUES 
('DB_ABILITY_LESS_EFFECTIVE_VS_LAND_UNITS', 'CLASS_NAVAL_RAIDER'),
('DB_ABILITY_LESS_EFFECTIVE_VS_WALLS', 'CLASS_NAVAL_RAIDER')
;

INSERT INTO UnitAbilities (UnitAbilityType, Name, Description, Permanent) VALUES 
('DB_ABILITY_LESS_EFFECTIVE_VS_LAND_UNITS', 'LOC_NAME_DB_ABILITY_LESS_EFFECTIVE_VS_LAND_UNITS', 'LOC_DESC_DB_ABILITY_LESS_EFFECTIVE_VS_LAND_UNITS', 1),
('DB_ABILITY_LESS_EFFECTIVE_VS_WALLS', 'LOC_NAME_DB_ABILITY_LESS_EFFECTIVE_VS_WALLS', 'LOC_DESC_DB_ABILITY_LESS_EFFECTIVE_VS_WALLS', 1)
;

INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES 
('DB_ABILITY_LESS_EFFECTIVE_VS_LAND_UNITS', 'DB_MOD_LESS_EFFECTIVE_VS_LAND_UNITS'),
('DB_ABILITY_LESS_EFFECTIVE_VS_WALLS', 'DB_MOD_LESS_EFFECTIVE_VS_WALLS')
;

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES 
('DB_MOD_LESS_EFFECTIVE_VS_LAND_UNITS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'DB_REQSET_ATTACKING_LAND_UNIT'),
('DB_MOD_LESS_EFFECTIVE_VS_WALLS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'DB_REQSET_ATTACKING_CITY_OR_ENCAMPMENT')
;

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('DB_MOD_LESS_EFFECTIVE_VS_LAND_UNITS', 'Amount', -17),
('DB_MOD_LESS_EFFECTIVE_VS_WALLS', 'Amount', -17)
;

INSERT INTO ModifierStrings (ModifierId, Context, Text) VALUES 
('DB_MOD_LESS_EFFECTIVE_VS_LAND_UNITS', 'Preview', 'LOC_COMBAT_DB_ABILITY_LESS_EFFECTIVE_VS_LAND_UNITS'),
('DB_MOD_LESS_EFFECTIVE_VS_WALLS', 'Preview', 'LOC_COMBAT_DB_ABILITY_LESS_EFFECTIVE_VS_WALLS')
;
