-- Naval Ranged
INSERT INTO UnitPromotionPrereqs ('UnitPromotion', 'PrereqUnitPromotion') VALUES
('PROMOTION_PREPARATORY_FIRE', 'PROMOTION_BOMBARDMENT'),
('PROMOTION_ROLLING_BARRAGE', 'PROMOTION_LINE_OF_BATTLE')
;