-- Bomber
INSERT INTO UnitPromotionPrereqs ('UnitPromotion', 'PrereqUnitPromotion') VALUES
('PROMOTION_LONG_RANGE', 'PROMOTION_TORPEDO_BOMBER'),
('PROMOTION_TACTICAL_MAINTENANCE', 'PROMOTION_CLOSE_AIR_SUPPORT')
;