-- Recon
DELETE FROM UnitPromotionPrereqs WHERE UnitPromotion IN 
	(SELECT UnitPromotionType FROM UnitPromotions WHERE PromotionClass = 'DB_PROMOTION_CLASS_LATER_RECON') ;

UPDATE UnitPromotions SET Level = 4, Column = 2 WHERE UnitPromotionType = 'PROMOTION_AMBUSH' ;
UPDATE UnitPromotions SET Level = 3, Column = 3 WHERE UnitPromotionType = 'PROMOTION_CAMOUFLAGE' ;
UPDATE UnitPromotions SET Level = 3, Column = 1 WHERE UnitPromotionType = 'PROMOTION_GUERRILLA' ;
UPDATE UnitPromotions SET Level = 2, Column = 3 WHERE UnitPromotionType = 'PROMOTION_SPYGLASS' ;

DELETE FROM UnitPromotionPrereqs WHERE UnitPromotion IN (
'PROMOTION_SPYGLASS',
'PROMOTION_GUERRILLA',
'PROMOTION_CAMOUFLAGE',
'PROMOTION_AMBUSH'
) ;

INSERT INTO UnitPromotionPrereqs ('UnitPromotion', 'PrereqUnitPromotion') VALUES
('PROMOTION_SENTRY', 'PROMOTION_RANGER'),
('PROMOTION_SENTRY', 'PROMOTION_ALPINE'),
('PROMOTION_SPYGLASS', 'PROMOTION_RANGER'),
('PROMOTION_SPYGLASS', 'PROMOTION_ALPINE'),
('PROMOTION_GUERRILLA', 'PROMOTION_SPYGLASS'),
('PROMOTION_GUERRILLA', 'PROMOTION_SENTRY'),
('PROMOTION_CAMOUFLAGE', 'PROMOTION_SPYGLASS'),
('PROMOTION_CAMOUFLAGE', 'PROMOTION_SENTRY'),
('PROMOTION_AMBUSH', 'PROMOTION_GUERRILLA'),
('PROMOTION_AMBUSH', 'PROMOTION_CAMOUFLAGE')
;