-- Ranged
DELETE FROM UnitPromotionPrereqs WHERE UnitPromotion IN 
	(SELECT UnitPromotionType FROM UnitPromotions WHERE PromotionClass = 'PROMOTION_CLASS_RANGED') ;

UPDATE UnitPromotions SET Level = 1, Column = 1 WHERE UnitPromotionType = 'PROMOTION_SUPPRESSION' ;
UPDATE UnitPromotions SET Level = 1, Column = 3 WHERE UnitPromotionType = 'PROMOTION_EMPLACEMENT' ;
UPDATE UnitPromotions SET Level = 2, Column = 1 WHERE UnitPromotionType = 'PROMOTION_VOLLEY' ;
UPDATE UnitPromotions SET Level = 2, Column = 3 WHERE UnitPromotionType = 'PROMOTION_INCENDIARIES' ;
UPDATE UnitPromotions SET Level = 3, Column = 1 WHERE UnitPromotionType = 'PROMOTION_ARROW_STORM' ;
UPDATE UnitPromotions SET Level = 3, Column = 3 WHERE UnitPromotionType = 'PROMOTION_GARRISON' ;


INSERT INTO UnitPromotionPrereqs ('UnitPromotion', 'PrereqUnitPromotion') VALUES
('PROMOTION_VOLLEY', 'PROMOTION_SUPPRESSION'),
('PROMOTION_VOLLEY', 'PROMOTION_EMPLACEMENT'),
('PROMOTION_INCENDIARIES', 'PROMOTION_SUPPRESSION'),
('PROMOTION_INCENDIARIES', 'PROMOTION_EMPLACEMENT'),
('PROMOTION_ARROW_STORM', 'PROMOTION_VOLLEY'),
('PROMOTION_ARROW_STORM', 'PROMOTION_INCENDIARIES'),
('PROMOTION_GARRISON', 'PROMOTION_VOLLEY'),
('PROMOTION_GARRISON', 'PROMOTION_INCENDIARIES'),
('PROMOTION_EXPERT_MARKSMAN', 'PROMOTION_ARROW_STORM'),
('PROMOTION_EXPERT_MARKSMAN', 'PROMOTION_GARRISON')
;


/*
DELETE FROM UnitPromotions WHERE UnitPromotionType IN ('PROMOTION_SUPPRESSION', 'PROMOTION_EMPLACEMENT') ;

INSERT INTO Types 
(Type,											Kind)
VALUES
('DB_PROMOTION_ARCHER_COVER_FIRE',			'KIND_PROMOTION'),
('DB_PROMOTION_ARCHER_SUPPRESSIVE_FIRE',	'KIND_PROMOTION')
;

INSERT INTO UnitPromotions
(UnitPromotionType,							Level,	Column,	PromotionClass,					Name,												Description) 
VALUES
('DB_PROMOTION_ARCHER_COVER_FIRE',			3,		1,		'PROMOTION_CLASS_RANGED',	'LOC_DB_PROMOTION_ARCHER_COVER_FIRE_NAME',			'LOC_DB_PROMOTION_ARCHER_COVER_FIRE_DESCRIPTION'),
('DB_PROMOTION_ARCHER_SUPPRESSIVE_FIRE',	3,		3,		'PROMOTION_CLASS_RANGED',	'LOC_DB_PROMOTION_ARCHER_SUPPRESSIVE_FIRE_NAME',	'LOC_DB_PROMOTION_ARCHER_SUPPRESSIVE_FIRE_DESCRIPTION')
;

INSERT INTO UnitPromotionPrereqs ('UnitPromotion', 'PrereqUnitPromotion') VALUES
('PROMOTION_ARROW_STORM', 'PROMOTION_VOLLEY'),
('PROMOTION_ARROW_STORM', 'PROMOTION_GARRISON'),
('PROMOTION_INCENDIARIES', 'PROMOTION_VOLLEY'),
('PROMOTION_INCENDIARIES', 'PROMOTION_GARRISON'),
('DB_PROMOTION_ARCHER_COVER_FIRE', 'PROMOTION_ARROW_STORM'),
('DB_PROMOTION_ARCHER_COVER_FIRE', 'PROMOTION_INCENDIARIES'),
('DB_PROMOTION_ARCHER_SUPPRESSIVE_FIRE', 'PROMOTION_ARROW_STORM'),
('DB_PROMOTION_ARCHER_SUPPRESSIVE_FIRE', 'PROMOTION_INCENDIARIES'),
('PROMOTION_EXPERT_MARKSMAN', 'DB_PROMOTION_ARCHER_COVER_FIRE'),
('PROMOTION_EXPERT_MARKSMAN', 'DB_PROMOTION_ARCHER_SUPPRESSIVE_FIRE')
;


INSERT INTO UnitPromotionModifiers
(UnitPromotionType,							ModifierId)
VALUES
('DB_PROMOTION_ARCHER_COVER_FIRE',			'DB_MOD_ARCHER_COVER_FIRE'),
('DB_PROMOTION_ARCHER_SUPPRESSIVE_FIRE',	'DB_MOD_ARCHER_SUPPRESSIVE_FIRE')
;

INSERT OR REPLACE INTO Modifiers
(ModifierId,													ModifierType,											SubjectRequirementSetId)
VALUES	
('DB_MOD_ARCHER_COVER_FIRE',									'MODIFIER_PLAYER_UNIT_ADJUST_FLANKING_BONUS_MODIFIER',	null),
('DB_MOD_ARCHER_SUPPRESSIVE_FIRE',								'MODIFIER_PLAYER_UNIT_ADJUST_SUPPORT_BONUS_MODIFIER',	null)
;

INSERT OR REPLACE INTO ModifierArguments
(ModifierId,													Name,					Value)
VALUES
('DB_MOD_ARCHER_COVER_FIRE',									'Percent',				200),
('DB_MOD_ARCHER_SUPPRESSIVE_FIRE',								'Percent',				200)
;

*/