-- Melee
DELETE FROM UnitPromotionPrereqs WHERE UnitPromotion IN 
	(SELECT UnitPromotionType FROM UnitPromotions WHERE PromotionClass = 'PROMOTION_CLASS_MELEE') ;

UPDATE UnitPromotions SET Level = 1, Column = 1 WHERE UnitPromotionType = 'PROMOTION_AMPHIBIOUS' ;
UPDATE UnitPromotions SET Level = 1, Column = 3 WHERE UnitPromotionType = 'PROMOTION_ZWEIHANDER' ;
UPDATE UnitPromotions SET Level = 2, Column = 1 WHERE UnitPromotionType = 'PROMOTION_BATTLECRY' ;
UPDATE UnitPromotions SET Level = 2, Column = 3 WHERE UnitPromotionType = 'PROMOTION_TORTOISE' ;
UPDATE UnitPromotions SET Level = 3, Column = 1 WHERE UnitPromotionType = 'PROMOTION_COMMANDO' ;

INSERT INTO UnitPromotionPrereqs ('UnitPromotion', 'PrereqUnitPromotion') VALUES
('PROMOTION_BATTLECRY', 'PROMOTION_AMPHIBIOUS'),
('PROMOTION_BATTLECRY', 'PROMOTION_ZWEIHANDER'),
('PROMOTION_TORTOISE', 'PROMOTION_AMPHIBIOUS'),
('PROMOTION_TORTOISE', 'PROMOTION_ZWEIHANDER'),
('PROMOTION_COMMANDO', 'PROMOTION_BATTLECRY'),
('PROMOTION_COMMANDO', 'PROMOTION_TORTOISE'),
('PROMOTION_URBAN_WARFARE', 'PROMOTION_BATTLECRY'),
('PROMOTION_URBAN_WARFARE', 'PROMOTION_TORTOISE'),
('PROMOTION_ELITE_GUARD', 'PROMOTION_COMMANDO'),
('PROMOTION_ELITE_GUARD', 'PROMOTION_URBAN_WARFARE')
;
