-- Naval Raider
DELETE FROM UnitPromotionPrereqs WHERE UnitPromotion IN 
	(SELECT UnitPromotionType FROM UnitPromotions WHERE PromotionClass = 'PROMOTION_CLASS_NAVAL_RAIDER') ;

INSERT INTO UnitPromotionPrereqs ('UnitPromotion', 'PrereqUnitPromotion') VALUES
('PROMOTION_SWIFT_KEEL', 'PROMOTION_LOOT'),
('PROMOTION_SWIFT_KEEL', 'PROMOTION_BOARDING'),
('PROMOTION_HOMING_TORPEDOES', 'PROMOTION_LOOT'),
('PROMOTION_HOMING_TORPEDOES', 'PROMOTION_BOARDING'),
('PROMOTION_OBSERVATION', 'PROMOTION_SWIFT_KEEL'),
('PROMOTION_OBSERVATION', 'PROMOTION_HOMING_TORPEDOES'),
('PROMOTION_SILENT_RUNNING', 'PROMOTION_SWIFT_KEEL'),
('PROMOTION_SILENT_RUNNING', 'PROMOTION_HOMING_TORPEDOES'),
('PROMOTION_WOLFPACK', 'PROMOTION_OBSERVATION'),
('PROMOTION_WOLFPACK', 'PROMOTION_SILENT_RUNNING')
;