INSERT OR REPLACE INTO Parameters (ParameterId, Name, Description, 
Domain, DefaultValue, ConfigurationGroup, ConfigurationId, GroupId, Visible, ReadOnly,
SupportsSinglePlayer, SupportsLANMultiplayer, SupportsInternetMultiplayer, SupportsHotSeat, SupportsPlayByCloud,
ChangeableAfterGameStart, ChangeableAfterPlayByCloudMatchCreate, SortIndex) VALUES 


-- Yields
('DB_ECONOMIC_OPTIONS', 'LOC_DB_GOLD_NAME', 'LOC_DB_ECONOMIC_OPTIONS_DESC', 
'text', 'Economic Options', 'Game', 'DB_ECONOMIC_OPTIONS', 'AdvancedOptions', 1, 1, 
1, 1, 1, 1, 1, 
0, 0, 999290),

('DB_LEARN_FROM_OTHER_CIVS', 'LOC_DB_LEARN_FROM_OTHER_CIVS_NAME', 'LOC_DB_LEARN_FROM_OTHER_CIVS_DESC', 
'bool', 1, 'Game', 'DB_LEARN_FROM_OTHER_CIVS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999291),

('DB_OLYMPIC_PANTHEONS', 'LOC_DB_OLYMPIC_PANTHEONS_NAME', 'LOC_DB_OLYMPIC_PANTHEONS_DESC', 
'bool', 1, 'Game', 'DB_OLYMPIC_PANTHEONS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999292),

('DB_ALL_CITIES_LIKE_SUGAR', 'LOC_DB_ALL_CITIES_LIKE_SUGAR_NAME', 'LOC_DB_ALL_CITIES_LIKE_SUGAR_DESC', 
'bool', 1, 'Game', 'DB_ALL_CITIES_LIKE_SUGAR', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999293),

('DB_GOLD_FROM_TOURISM', 'LOC_DB_GOLD_FROM_TOURISM_NAME', 'LOC_DB_GOLD_FROM_TOURISM_DESC', 
'bool', 1, 'Game', 'DB_GOLD_FROM_TOURISM', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999294),

('DB_PEOPLE_CREATE', 'LOC_DB_PEOPLE_CREATE_NAME', 'LOC_DB_PEOPLE_CREATE_DESC', 
'bool', 1, 'Game', 'DB_PEOPLE_CREATE', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999295),

('DB_WATER_MILL_ALL_FARMS', 'LOC_DB_WATER_MILL_ALL_FARMS_NAME', 'LOC_DB_WATER_MILL_ALL_FARMS_DESC', 
'bool', 1, 'Game', 'DB_WATER_MILL_ALL_FARMS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999296),

('DB_DISTRICTS_ON_RESOURCES', 'LOC_DB_DISTRICTS_ON_RESOURCES_NAME', 'LOC_DB_DISTRICTS_ON_RESOURCES_DESC', 
'bool', 1, 'Game', 'DB_DISTRICTS_ON_RESOURCES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999297),

('DB_BUILDERS_CAN_BUILD_ROADS', 'LOC_DB_BUILDERS_CAN_BUILD_ROADS_NAME', 'LOC_DB_BUILDERS_CAN_BUILD_ROADS_DESC', 
'bool', 1, 'Game', 'DB_BUILDERS_CAN_BUILD_ROADS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999298),

('DB_GREAT_MERCHANTS_GRANT_TRADER', 'LOC_DB_GREAT_MERCHANTS_GRANT_TRADER_NAME', 'LOC_DB_GREAT_MERCHANTS_GRANT_TRADER_DESC', 
'bool', 1, 'Game', 'DB_GREAT_MERCHANTS_GRANT_TRADER', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999299),

('DB_BETTER_GREAT_SCIENTISTS', 'LOC_DB_BETTER_GREAT_SCIENTISTS_NAME', 'LOC_DB_BETTER_GREAT_SCIENTISTS_DESC', 
'bool', 1, 'Game', 'DB_BETTER_GREAT_SCIENTISTS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999300),

('DB_BETTER_TRADE_ROUTES', 'LOC_DB_BETTER_TRADE_ROUTES_NAME', 'LOC_DB_BETTER_TRADE_ROUTES_DESC', 
'bool', 1, 'Game', 'DB_BETTER_TRADE_ROUTES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999301),

('DB_LIGHTHOUSES_REMOVE_TRADE_ROUTE', 'LOC_DB_LIGHTHOUSES_REMOVE_TRADE_ROUTE_NAME', 'LOC_DB_LIGHTHOUSES_REMOVE_TRADE_ROUTE_DESC', 
'bool', 1, 'Game', 'DB_LIGHTHOUSES_REMOVE_TRADE_ROUTE', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999302),

('DB_BETTER_GOVERNMENT_PLAZA', 'LOC_DB_BETTER_GOVERNMENT_PLAZA_NAME', 'LOC_DB_BETTER_GOVERNMENT_PLAZA_DESC', 
'bool', 1, 'Game', 'DB_BETTER_GOVERNMENT_PLAZA', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999303),

('DB_BETTER_DIPLOMATIC_QUARTER', 'LOC_DB_BETTER_DIPLOMATIC_QUARTER_NAME', 'LOC_DB_BETTER_DIPLOMATIC_QUARTER_DESC', 
'bool', 1, 'Game', 'DB_BETTER_DIPLOMATIC_QUARTER', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999304),

('DB_COURTHOUSES', 'LOC_DB_COURTHOUSES_NAME', 'LOC_DB_COURTHOUSES_DESC', 
'bool', 1, 'Game', 'DB_COURTHOUSES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999305),

('DB_BETTER_GOVERNORS', 'LOC_DB_BETTER_GOVERNORS_NAME', 'LOC_DB_BETTER_GOVERNORS_DESC', 
'bool', 1, 'Game', 'DB_BETTER_GOVERNORS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999306),

('DB_SCIENCE_PER_POP', 'LOC_DB_SCIENCE_PER_POP_NAME', 'LOC_DB_SCIENCE_PER_POP_DESC', 
'DBScienceRate', 25, 'Game', 'DB_SCIENCE_PER_POP', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999307),

('DB_REMOVE_TECH_BOOSTS', 'LOC_DB_REMOVE_TECH_BOOSTS_NAME', 'LOC_DB_REMOVE_TECH_BOOSTS_DESC', 
'bool', 1, 'Game', 'DB_REMOVE_TECH_BOOSTS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999308),

('DB_CULTURE_PER_POP', 'LOC_DB_CULTURE_PER_POP_NAME', 'LOC_DB_CULTURE_PER_POP_DESC', 
'DBCultureRate', 25, 'Game', 'DB_CULTURE_PER_POP', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999309),

('DB_REMOVE_CIVIC_BOOSTS', 'LOC_DB_REMOVE_CIVIC_BOOSTS_NAME', 'LOC_DB_REMOVE_CIVIC_BOOSTS_DESC', 
'bool', 1, 'Game', 'DB_REMOVE_CIVIC_BOOSTS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999310),

('DB_THEATER_SQUARE_BETTER_ADJACENCIES', 'LOC_DB_THEATER_SQUARE_BETTER_ADJACENCIES_NAME', 'LOC_DB_THEATER_SQUARE_BETTER_ADJACENCIES_DESC', 
'bool', 1, 'Game', 'DB_THEATER_SQUARE_BETTER_ADJACENCIES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999311),

('DB_MONUMENTS_NO_CULTURE', 'LOC_DB_MONUMENTS_NO_CULTURE_NAME', 'LOC_DB_MONUMENTS_NO_CULTURE_DESC', 
'bool', 1, 'Game', 'DB_MONUMENTS_NO_CULTURE', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999312),

('DB_MONUMENTS_PROVIDE_BUILD_CHARGE', 'LOC_DB_MONUMENTS_PROVIDE_BUILD_CHARGE_NAME', 'LOC_DB_MONUMENTS_PROVIDE_BUILD_CHARGE_DESC', 
'bool', 1, 'Game', 'DB_MONUMENTS_PROVIDE_BUILD_CHARGE', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999313),

('DB_CITYSTATES_ARENT_BACKWARDS', 'LOC_DB_CITYSTATES_ARENT_BACKWARDS_NAME', 'LOC_DB_CITYSTATES_ARENT_BACKWARDS_DESC', 
'bool', 1, 'Game', 'DB_CITYSTATES_ARENT_BACKWARDS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999314),


-- LOYALTY
('DB_LOYALTY_OPTIONS', 'LOC_DB_GOLD_NAME', 'LOC_DB_LOYALTY_OPTIONS_DESC', 
'text', 'Loyalty Options', 'Game', 'DB_LOYALTY_OPTIONS', 'AdvancedOptions', 1, 1, 
1, 1, 1, 1, 1, 
0, 0, 999320),

('DB_LOYALTY_MATTERS', 'LOC_DB_LOYALTY_MATTERS_NAME', 'LOC_DB_LOYALTY_MATTERS_DESC', 
'bool', 1, 'Game', 'DB_LOYALTY_MATTERS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999321),

('DB_DISLOYAL_INFORMANTS', 'LOC_DB_DISLOYAL_INFORMANTS_NAME', 'LOC_DB_DISLOYAL_INFORMANTS_DESC', 
'bool', 1, 'Game', 'DB_DISLOYAL_INFORMANTS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999322),


-- MILITARY
('DB_MILITARY_OPTIONS', 'LOC_DB_GOLD_NAME', 'LOC_DB_MILITARY_OPTIONS_DESC', 
'text', 'Military Options', 'Game', 'DB_MILITARY_OPTIONS', 'AdvancedOptions', 1, 1, 
1, 1, 1, 1, 1, 
0, 0, 999330),

('DB_TURNS_FOR_PEACE', 'LOC_DB_TURNS_FOR_PEACE_NAME', 'LOC_DB_TURNS_FOR_PEACE_DESC', 
'DBTurnsForPeace', 15, 'Game', 'DB_TURNS_FOR_PEACE', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999331),

('DB_BATTLE_NOTIFICATIONS', 'LOC_DB_BATTLE_NOTIFICATIONS_NAME', 'LOC_DB_BATTLE_NOTIFICATIONS_DESC', 
'bool', 1, 'Game', 'DB_BATTLE_NOTIFICATIONS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999332),

('DB_EXPERIENCE_FROM_OBSERVATION', 'LOC_DB_EXPERIENCE_FROM_OBSERVATION_NAME', 'LOC_DB_EXPERIENCE_FROM_OBSERVATION_DESC', 
'bool', 1, 'Game', 'DB_EXPERIENCE_FROM_OBSERVATION', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999333),

('DB_TREES_HIDE_UNITS', 'LOC_DB_TREES_HIDE_UNITS_NAME', 'LOC_DB_TREES_HIDE_UNITS_DESC', 
'bool', 1, 'Game', 'DB_TREES_HIDE_UNITS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999334),

('DB_BETTER_SCOUTS', 'LOC_DB_BETTER_SCOUTS_NAME', 'LOC_DB_BETTER_SCOUTS_DESC', 
'bool', 1, 'Game', 'DB_BETTER_SCOUTS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999335),

('DB_BETTER_WARFARE', 'LOC_DB_BETTER_WARFARE_NAME', 'LOC_DB_BETTER_WARFARE_DESC', 
'bool', 1, 'Game', 'DB_BETTER_WARFARE', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999336),

('DB_NO_BAD_HUTS', 'LOC_DB_NO_BAD_HUTS_NAME', 'LOC_DB_NO_BAD_HUTS_DESC', 
'bool', 1, 'Game', 'DB_NO_BAD_HUTS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999337),

('DB_BALANCED_WALLS', 'LOC_DB_BALANCED_WALLS_NAME', 'LOC_DB_BALANCED_WALLS_DESC', 
'bool', 1, 'Game', 'DB_BALANCED_WALLS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999338),

('DB_ENGINEERS_RUSH_WALLS', 'LOC_DB_ENGINEERS_RUSH_WALLS_NAME', 'LOC_DB_ENGINEERS_RUSH_WALLS_DESC', 
'bool', 1, 'Game', 'DB_ENGINEERS_RUSH_WALLS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999339),

('DB_ENGINEERS_AS_SAPPERS', 'LOC_DB_ENGINEERS_AS_SAPPERS_NAME', 'LOC_DB_ENGINEERS_AS_SAPPERS_DESC', 
'bool', 1, 'Game', 'DB_ENGINEERS_AS_SAPPERS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999340),

('DB_SIEGE_UNITS_NO_EXTRA_MOVEMENT', 'LOC_DB_SIEGE_UNITS_NO_EXTRA_MOVEMENT_NAME', 'LOC_DB_SIEGE_UNITS_NO_EXTRA_MOVEMENT_DESC', 
'bool', 1, 'Game', 'DB_SIEGE_UNITS_NO_EXTRA_MOVEMENT', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999341),

('DB_EARLIER_WARS_OF_RELIGION', 'LOC_DB_EARLIER_WARS_OF_RELIGION_NAME', 'LOC_DB_EARLIER_WARS_OF_RELIGION_DESC', 
'bool', 1, 'Game', 'DB_EARLIER_WARS_OF_RELIGION', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999342),

('DB_ALL_MEN_ARE_MORTAL', 'LOC_DB_ALL_MEN_ARE_MORTAL_NAME', 'LOC_DB_ALL_MEN_ARE_MORTAL_DESC', 
'bool', 1, 'Game', 'DB_ALL_MEN_ARE_MORTAL', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999343),


-- RELIGION
('DB_RELIGION_OPTIONS', 'LOC_DB_GOLD_NAME', 'LOC_DB_RELIGION_OPTIONS_DESC', 
'text', 'Religion Options', 'Game', 'DB_RELIGION_OPTIONS', 'AdvancedOptions', 1, 1, 
1, 1, 1, 1, 1, 
0, 0, 999350),

('DB_SOLI_DEO_GLORIA', 'LOC_DB_SOLI_DEO_GLORIA_NAME', 'LOC_DB_SOLI_DEO_GLORIA_DESC', 
'bool', 1, 'Game', 'DB_SOLI_DEO_GLORIA', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999351),

('DB_PANTHEON_OBELISK', 'LOC_DB_PANTHEON_OBELISK_NAME', 'LOC_DB_PANTHEON_OBELISK_DESC', 
'bool', 1, 'Game', 'DB_PANTHEON_OBELISK', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999352),

('DB_RELIGIOUS_UNITS_TWO_MOVES', 'LOC_DB_RELIGIOUS_UNITS_TWO_MOVES_NAME', 'LOC_DB_RELIGIOUS_UNITS_TWO_MOVES_DESC', 
'bool', 1, 'Game', 'DB_RELIGIOUS_UNITS_TWO_MOVES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999353),

('DB_EMBARKED_RELIGIOUS_UNITS', 'LOC_DB_EMBARKED_RELIGIOUS_UNITS_NAME', 'LOC_DB_EMBARKED_RELIGIOUS_UNITS_DESC', 
'bool', 1, 'Game', 'DB_EMBARKED_RELIGIOUS_UNITS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999354),

('DB_ALL_HS3_BUILDINGS', 'LOC_DB_ALL_HS3_BUILDINGS_NAME', 'LOC_DB_ALL_HS3_BUILDINGS_DESC', 
'bool', 1, 'Game', 'DB_ALL_HS3_BUILDINGS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999355),

('DB_DONT_NEED_INQUISITION', 'LOC_DB_DONT_NEED_INQUISITION_NAME', 'LOC_DB_DONT_NEED_INQUISITION_DESC', 
'bool', 1, 'Game', 'DB_DONT_NEED_INQUISITION', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999356),

('DB_INQUISITORS_FROM_SHRINES', 'LOC_DB_INQUISITORS_FROM_SHRINES_NAME', 'LOC_DB_INQUISITORS_FROM_SHRINES_DESC', 
'bool', 1, 'Game', 'DB_INQUISITORS_FROM_SHRINES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999357),

('DB_ONE_CLEANSE_INQUISITORS', 'LOC_DB_ONE_CLEANSE_INQUISITORS_NAME', 'LOC_DB_ONE_CLEANSE_INQUISITORS_DESC', 
'bool', 1, 'Game', 'DB_ONE_CLEANSE_INQUISITORS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999358),

('DB_CATHEDRALS_HOLD_RELICS', 'LOC_DB_CATHEDRALS_HOLD_RELICS_NAME', 'LOC_DB_CATHEDRALS_HOLD_RELICS_DESC', 
'bool', 1, 'Game', 'DB_CATHEDRALS_HOLD_RELICS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999359),

('DB_KOTOKUIN_TO_THEOLGY', 'LOC_DB_KOTOKUIN_TO_THEOLGY_NAME', 'LOC_DB_KOTOKUIN_TO_THEOLGY_DESC', 
'bool', 1, 'Game', 'DB_KOTOKUIN_TO_THEOLGY', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999360),


-- PURELY COSMETIC
('DB_COSMETIC_OPTIONS', 'LOC_DB_GOLD_NAME', 'LOC_DB_COSMETIC_OPTIONS_DESC', 
'text', 'Cosmetic Options', 'Game', 'DB_COSMETIC_OPTIONS', 'AdvancedOptions', 1, 1, 
1, 1, 1, 1, 1, 
0, 0, 999370),

('DB_NO_MORE_STIRRINGS', 'LOC_DB_NO_MORE_STIRRINGS_NAME', 'LOC_DB_NO_MORE_STIRRINGS_DESC', 
'bool', 1, 'Game', 'DB_NO_MORE_STIRRINGS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999371),



-- GOOD FOR MULTIPLAYER, ALSO WORK ON SINGLEPLAYER
('DB_OK_SINGLEPLAYER_OPTIONS', 'LOC_DB_GOLD_NAME', 'LOC_DB_OK_SINGLEPLAYER_OPTIONS_DESC', 
'text', 'Multiplayer Options (that work in Single Player)', 'Game', 'DB_OK_SINGLEPLAYER_OPTIONS', 'AdvancedOptions', 1, 1, 
1, 1, 1, 1, 1, 
0, 0, 999380),

('DB_REMOVE_CIV_LEADER_TRAITS', 'LOC_DB_REMOVE_CIV_LEADER_TRAITS_NAME', 'LOC_DB_REMOVE_CIV_LEADER_TRAITS_DESC', 
'bool', 1, 'Game', 'DB_REMOVE_CIV_LEADER_TRAITS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999381),

('DB_REMOVE_UNIT_UPGRADES', 'LOC_DB_REMOVE_UNIT_UPGRADES_NAME', 'LOC_DB_REMOVE_UNIT_UPGRADES_DESC', 
'bool', 1, 'Game', 'DB_REMOVE_UNIT_UPGRADES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999382),

('DB_REMOVE_FOREIGN_INFO', 'LOC_DB_REMOVE_FOREIGN_INFO_NAME', 'LOC_DB_REMOVE_FOREIGN_INFO_DESC', 
'bool', 1, 'Game', 'DB_REMOVE_FOREIGN_INFO', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999383),

('DB_NO_CITY_TRADES', 'LOC_DB_NO_CITY_TRADES_NAME', 'LOC_DB_NO_CITY_TRADES_DESC', 
'bool', 1, 'Game', 'DB_NO_CITY_TRADES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999384),

('DB_DOUBLE_SPIES', 'LOC_DB_DOUBLE_SPIES_NAME', 'LOC_DB_DOUBLE_SPIES_DESC', 
'bool', 1, 'Game', 'DB_DOUBLE_SPIES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999385),

('DB_REMOVE_GOLDEN_DARK_AGES', 'LOC_DB_REMOVE_GOLDEN_DARK_AGES_NAME', 'LOC_DB_REMOVE_GOLDEN_DARK_AGES_DESC', 
'bool', 1, 'Game', 'DB_REMOVE_GOLDEN_DARK_AGES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999386),

('DB_REMOVE_WORLD_CONGRESS', 'LOC_DB_REMOVE_WORLD_CONGRESS_NAME', 'LOC_DB_REMOVE_WORLD_CONGRESS_DESC', 
'bool', 1, 'Game', 'DB_REMOVE_WORLD_CONGRESS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999387),

('DB_REMOVE_EMERGENCIES', 'LOC_DB_REMOVE_EMERGENCIES_NAME', 'LOC_DB_REMOVE_EMERGENCIES_DESC', 
'bool', 1, 'Game', 'DB_REMOVE_EMERGENCIES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999388),

('DB_REMOVE_PLUNDER_POLICIES', 'LOC_DB_REMOVE_PLUNDER_POLICIES_NAME', 'LOC_DB_REMOVE_PLUNDER_POLICIES_DESC', 
'bool', 1, 'Game', 'DB_REMOVE_PLUNDER_POLICIES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999389),

('DB_REMOVE_ONE_TURN_POLICIES', 'LOC_DB_REMOVE_ONE_TURN_POLICIES_NAME', 'LOC_DB_REMOVE_ONE_TURN_POLICIES_DESC', 
'bool', 1, 'Game', 'DB_REMOVE_ONE_TURN_POLICIES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999390),


-- DON'T REALLY WORK IN SINGLE-PLAYER
('DB_ONLY_MULTIPLAYER_OPTIONS', 'LOC_DB_GOLD_NAME', 'LOC_DB_ONLY_MULTIPLAYER_OPTIONS_DESC', 
'text', 'Only Multiplayer Options', 'Game', 'DB_ONLY_MULTIPLAYER_OPTIONS', 'AdvancedOptions', 1, 1, 
1, 1, 1, 1, 1, 
0, 0, 999400),

('DB_REMOVE_CONDEMN_HERETIC', 'LOC_DB_REMOVE_CONDEMN_HERETIC_NAME', 'LOC_DB_REMOVE_CONDEMN_HERETIC_DESC', 
'bool', 0, 'Game', 'DB_REMOVE_CONDEMN_HERETIC', 'AdvancedOptions', 1, 0, 
1, 0, 0, 0, 0, 
0, 0, 999401),

('DB_REMOVE_CONDEMN_HERETIC', 'LOC_DB_REMOVE_CONDEMN_HERETIC_NAME', 'LOC_DB_REMOVE_CONDEMN_HERETIC_DESC', 
'bool', 1, 'Game', 'DB_REMOVE_CONDEMN_HERETIC', 'AdvancedOptions', 1, 0, 
0, 1, 1, 1, 1, 
0, 0, 999402),

('DB_MILITARY_ALLIANCE_ONLY_SHARE_VISION', 'LOC_DB_MILITARY_ALLIANCE_ONLY_SHARE_VISION_NAME', 'LOC_DB_MILITARY_ALLIANCE_ONLY_SHARE_VISION_DESC', 
'bool', 0, 'Game', 'DB_MILITARY_ALLIANCE_ONLY_SHARE_VISION', 'AdvancedOptions', 1, 0, 
1, 0, 0, 0, 0, 
0, 0, 999403),

('DB_MILITARY_ALLIANCE_ONLY_SHARE_VISION', 'LOC_DB_MILITARY_ALLIANCE_ONLY_SHARE_VISION_NAME', 'LOC_DB_MILITARY_ALLIANCE_ONLY_SHARE_VISION_DESC', 
'bool', 1, 'Game', 'DB_MILITARY_ALLIANCE_ONLY_SHARE_VISION', 'AdvancedOptions', 1, 0, 
0, 1, 1, 1, 1, 
0, 0, 999404),

('DB_DIFFICULTY_COMBAT_STRENGTH', 'LOC_DB_DIFFICULTY_COMBAT_STRENGTH_NAME', 'LOC_DB_DIFFICULTY_COMBAT_STRENGTH_DESC', 
'bool', 0, 'Game', 'DB_DIFFICULTY_COMBAT_STRENGTH', 'AdvancedOptions', 1, 0, 
1, 0, 0, 0, 0, 
0, 0, 999405),

('DB_DIFFICULTY_COMBAT_STRENGTH', 'LOC_DB_DIFFICULTY_COMBAT_STRENGTH_NAME', 'LOC_DB_DIFFICULTY_COMBAT_STRENGTH_DESC', 
'bool', 1, 'Game', 'DB_DIFFICULTY_COMBAT_STRENGTH', 'AdvancedOptions', 1, 0, 
0, 1, 1, 1, 1, 
0, 0, 999406),

('DB_GREAT_PEOPLE_COME_FROM_PEOPLE', 'LOC_DB_GREAT_PEOPLE_COME_FROM_PEOPLE_NAME', 'LOC_DB_GREAT_PEOPLE_COME_FROM_PEOPLE_DESC', 
'bool', 0, 'Game', 'DB_GREAT_PEOPLE_COME_FROM_PEOPLE', 'AdvancedOptions', 1, 0, 
1, 0, 0, 0, 0, 
0, 0, 999407),

('DB_GREAT_PEOPLE_COME_FROM_PEOPLE', 'LOC_DB_GREAT_PEOPLE_COME_FROM_PEOPLE_NAME', 'LOC_DB_GREAT_PEOPLE_COME_FROM_PEOPLE_DESC', 
'bool', 1, 'Game', 'DB_GREAT_PEOPLE_COME_FROM_PEOPLE', 'AdvancedOptions', 1, 0, 
0, 1, 1, 1, 1, 
0, 0, 999408),

('DB_ALL_CUSTOM_NAMES', 'LOC_DB_ALL_CUSTOM_NAMES_NAME', 'LOC_DB_ALL_CUSTOM_NAMES_DESC', 
'bool', 0, 'Game', 'DB_ALL_CUSTOM_NAMES', 'AdvancedOptions', 1, 0, 
1, 0, 0, 0, 0, 
0, 0, 999409),

('DB_ALL_CUSTOM_NAMES', 'LOC_DB_ALL_CUSTOM_NAMES_NAME', 'LOC_DB_ALL_CUSTOM_NAMES_DESC', 
'bool', 1, 'Game', 'DB_ALL_CUSTOM_NAMES', 'AdvancedOptions', 1, 0, 
0, 1, 1, 1, 1, 
0, 0, 999410),

('DB_TEAM_ADJUSTMENTS', 'LOC_NAME_DB_TEAM_ADJUSTMENTS', 'LOC_DESC_DB_TEAM_ADJUSTMENTS', 
'bool', 0, 'Game', 'DB_TEAM_ADJUSTMENTS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999411),


-- HOP ONS
('DB_DEPRECATED_OPTIONS', 'LOC_DB_GOLD_NAME', 'LOC_DB_DEPRECATED_OPTIONS_DESC', 
'text', 'Hop-ons', 'Game', 'DB_DEPRECATED_OPTIONS', 'AdvancedOptions', 1, 1, 
1, 1, 1, 1, 1, 
0, 0, 999420),

('DB_REMOVE_GOVERNMENT_PLAZAS', 'LOC_DB_REMOVE_GOVERNMENT_PLAZAS_NAME', 'LOC_DB_REMOVE_GOVERNMENT_PLAZAS_DESC', 
'bool', 0, 'Game', 'DB_REMOVE_GOVERNMENT_PLAZAS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999421),

('DB_OLYMPIC_PANTHEONS_COMBAT', 'LOC_DB_OLYMPIC_PANTHEONS_COMBAT_NAME', 'LOC_DB_OLYMPIC_PANTHEONS_COMBAT_DESC', 
'bool', 0, 'Game', 'DB_OLYMPIC_PANTHEONS_COMBAT', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999422),

('DB_BETTER_ROADS', 'LOC_DB_BETTER_ROADS_NAME', 'LOC_DB_BETTER_ROADS_DESC', 
'bool', 0, 'Game', 'DB_BETTER_ROADS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999423),

('DB_REVEAL_STRATEGIC_RESOURCES', 'LOC_DB_REVEAL_STRATEGIC_RESOURCES_NAME', 'LOC_DB_REVEAL_STRATEGIC_RESOURCES_DESC', 
'bool', 0, 'Game', 'DB_REVEAL_STRATEGIC_RESOURCES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999424),

('DB_MORE_BELIEFS', 'LOC_DB_MORE_BELIEFS_NAME', 'LOC_DB_MORE_BELIEFS_DESC', 
'bool', 0, 'Game', 'DB_MORE_BELIEFS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999425),

('DB_DOUBLE_BELIEFS', 'LOC_DB_DOUBLE_BELIEFS_NAME', 'LOC_DB_DOUBLE_BELIEFS_DESC', 
'bool', 0, 'Game', 'DB_DOUBLE_BELIEFS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999426),

('DB_COMBAT_DOESNT_PRESSURE', 'LOC_DB_COMBAT_DOESNT_PRESSURE_NAME', 'LOC_DB_COMBAT_DOESNT_PRESSURE_DESC', 
'bool', 0, 'Game', 'DB_COMBAT_DOESNT_PRESSURE', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999427),

('DB_BUY_HSBUILDINGS_WITH_FAITH', 'LOC_DB_BUY_HSBUILDINGS_WITH_FAITH_NAME', 'LOC_DB_BUY_HSBUILDINGS_WITH_FAITH_DESC', 
'bool', 0, 'Game', 'DB_BUY_HSBUILDINGS_WITH_FAITH', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999428),

('DB_MARTYRS_LOSE_CS', 'LOC_DB_MARTYRS_LOSE_CS_NAME', 'LOC_DB_MARTYRS_LOSE_CS_DESC', 
'bool', 0, 'Game', 'DB_MARTYRS_LOSE_CS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999429),

('DB_REMOVE_HEATHEN_CONVERSION', 'LOC_DB_REMOVE_HEATHEN_CONVERSION_NAME', 'LOC_DB_REMOVE_HEATHEN_CONVERSION_DESC', 
'bool', 0, 'Game', 'DB_REMOVE_HEATHEN_CONVERSION', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 999430) 
;


INSERT OR REPLACE INTO DomainValues (Domain, Name, Description, SortIndex, Value) VALUES
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_DISABLED_NAME', '', 0, 999),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_0_NAME', 'LOC_DB_SCIENCE_PER_POP_0_DESC', 1, 0),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_5_NAME', 'LOC_DB_SCIENCE_PER_POP_5_DESC', 5, 5),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_10_NAME', 'LOC_DB_SCIENCE_PER_POP_10_DESC', 10, 10),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_15_NAME', 'LOC_DB_SCIENCE_PER_POP_15_DESC', 15, 15),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_20_NAME', 'LOC_DB_SCIENCE_PER_POP_20_DESC', 20, 20),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_25_NAME', 'LOC_DB_SCIENCE_PER_POP_25_DESC', 25, 25),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_30_NAME', 'LOC_DB_SCIENCE_PER_POP_30_DESC', 30, 30),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_35_NAME', 'LOC_DB_SCIENCE_PER_POP_35_DESC', 35, 35),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_40_NAME', 'LOC_DB_SCIENCE_PER_POP_40_DESC', 40, 40),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_45_NAME', 'LOC_DB_SCIENCE_PER_POP_45_DESC', 45, 45),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_50_NAME', 'LOC_DB_SCIENCE_PER_POP_50_DESC', 50, 50),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_55_NAME', 'LOC_DB_SCIENCE_PER_POP_55_DESC', 55, 55),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_60_NAME', 'LOC_DB_SCIENCE_PER_POP_60_DESC', 60, 60),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_65_NAME', 'LOC_DB_SCIENCE_PER_POP_65_DESC', 65, 65),
('DBScienceRate', 'LOC_DB_SCIENCE_PER_POP_70_NAME', 'LOC_DB_SCIENCE_PER_POP_70_DESC', 70, 70),

('DBCultureRate', 'LOC_DB_CULTURE_PER_POP_DISABLED_NAME', '', 0, 999),
('DBCultureRate', 'LOC_DB_CULTURE_PER_POP_0_NAME', 'LOC_DB_CULTURE_PER_POP_0_DESC', 1, 0),
('DBCultureRate', 'LOC_DB_CULTURE_PER_POP_5_NAME', 'LOC_DB_CULTURE_PER_POP_5_DESC', 5, 5),
('DBCultureRate', 'LOC_DB_CULTURE_PER_POP_10_NAME', 'LOC_DB_CULTURE_PER_POP_10_DESC', 10, 10),
('DBCultureRate', 'LOC_DB_CULTURE_PER_POP_15_NAME', 'LOC_DB_CULTURE_PER_POP_15_DESC', 15, 15),
('DBCultureRate', 'LOC_DB_CULTURE_PER_POP_20_NAME', 'LOC_DB_CULTURE_PER_POP_20_DESC', 20, 20),
('DBCultureRate', 'LOC_DB_CULTURE_PER_POP_25_NAME', 'LOC_DB_CULTURE_PER_POP_25_DESC', 25, 25),
('DBCultureRate', 'LOC_DB_CULTURE_PER_POP_30_NAME', 'LOC_DB_CULTURE_PER_POP_30_DESC', 30, 30),

('DBTurnsForPeace', 'LOC_DB_TURNS_FOR_PEACE_DISABLED_NAME', '', 0, 999),
('DBTurnsForPeace', 'LOC_DB_TURNS_FOR_PEACE_05_NAME', 'LOC_DB_TURNS_FOR_PEACE_05_DESC', 5, 5),
('DBTurnsForPeace', 'LOC_DB_TURNS_FOR_PEACE_10_NAME', 'LOC_DB_TURNS_FOR_PEACE_10_DESC', 10, 10),
('DBTurnsForPeace', 'LOC_DB_TURNS_FOR_PEACE_15_NAME', 'LOC_DB_TURNS_FOR_PEACE_15_DESC', 15, 15),
('DBTurnsForPeace', 'LOC_DB_TURNS_FOR_PEACE_20_NAME', 'LOC_DB_TURNS_FOR_PEACE_20_DESC', 20, 20),
('DBTurnsForPeace', 'LOC_DB_TURNS_FOR_PEACE_25_NAME', 'LOC_DB_TURNS_FOR_PEACE_25_DESC', 25, 25),
('DBTurnsForPeace', 'LOC_DB_TURNS_FOR_PEACE_30_NAME', 'LOC_DB_TURNS_FOR_PEACE_30_DESC', 30, 30),
('DBTurnsForPeace', 'LOC_DB_TURNS_FOR_PEACE_35_NAME', 'LOC_DB_TURNS_FOR_PEACE_35_DESC', 35, 35),
('DBTurnsForPeace', 'LOC_DB_TURNS_FOR_PEACE_40_NAME', 'LOC_DB_TURNS_FOR_PEACE_40_DESC', 40, 40),
('DBTurnsForPeace', 'LOC_DB_TURNS_FOR_PEACE_45_NAME', 'LOC_DB_TURNS_FOR_PEACE_45_DESC', 45, 45),
('DBTurnsForPeace', 'LOC_DB_TURNS_FOR_PEACE_50_NAME', 'LOC_DB_TURNS_FOR_PEACE_50_DESC', 50, 50),
('DBTurnsForPeace', 'LOC_DB_TURNS_FOR_PEACE_55_NAME', 'LOC_DB_TURNS_FOR_PEACE_55_DESC', 55, 55),
('DBTurnsForPeace', 'LOC_DB_TURNS_FOR_PEACE_60_NAME', 'LOC_DB_TURNS_FOR_PEACE_60_DESC', 60, 60)
;



-- Setting our preferences for the built-in parameters...
-- Parameters with trailing -- don't update, use a different default value (not sure why)

UPDATE Parameters SET DefaultValue = 1 WHERE ConfigurationId = 'PRIVATE_GAME' ;							--
UPDATE Parameters SET DefaultValue = 'TURNPHASE_DYNAMIC' WHERE ConfigurationId = 'TURN_PHASE_TYPE' ;

UPDATE Parameters SET DefaultValue = 14 WHERE ConfigurationId = 'CITY_STATE_COUNT' ;					--
UPDATE Parameters SET DefaultValue = 0 WHERE ConfigurationId = 'GAME_REALISM' ;							--

UPDATE Parameters SET DefaultValue = 'GAMESPEED_STANDARD' WHERE ConfigurationId = 'GAME_SPEED_TYPE' ;	--
UPDATE Parameters SET DefaultValue = 'Terra.lua' WHERE ConfigurationId = 'MAP_SCRIPT' ;					--
UPDATE Parameters SET DefaultValue = 4 WHERE ConfigurationId = 'resources' ;
UPDATE Parameters SET DefaultValue = 0 WHERE ConfigurationId = 'BBSStratRes' ;
UPDATE Parameters SET DefaultValue = 2 WHERE ConfigurationId = 'BBSNatural' ;

-- UPDATE Parameters SET DefaultValue = '' WHERE ConfigurationId = 'EXCLUDE_CITY_STATES' ;				--
-- UPDATE Parameters SET DefaultValue = '' WHERE ConfigurationId = 'EXCLUDE_NATURAL_WONDERS' ;			--

UPDATE Parameters SET DefaultValue = 4 WHERE ConfigurationId = 'world_age' ;
UPDATE Parameters SET DefaultValue = 3 WHERE ConfigurationId = 'BBSRidge' ;
UPDATE Parameters SET DefaultValue = 4 WHERE ConfigurationId = 'temperature' ;
UPDATE Parameters SET DefaultValue = 4 WHERE ConfigurationId = 'rainfall' ;
UPDATE Parameters SET DefaultValue = 1 WHERE ConfigurationId = 'sea_level' ;

UPDATE Victories SET EnabledByDefault = 0 WHERE VictoryType = 'VICTORY_SCORE' ;
UPDATE Victories SET EnabledByDefault = 0 WHERE VictoryType = 'VICTORY_DIPLOMATIC' ;					--

UPDATE Parameters SET DefaultValue = 1 WHERE ConfigurationId = 'NO_TEAMS' ;








UPDATE Parameters SET DefaultValue = 1 WHERE ConfigurationId IN 
('GAMEMODE_BARBARIAN_CLANS',
'GAMEMODE_TREE_RANDOMIZER') ;