INSERT OR IGNORE INTO Tags (Tag, Vocabulary) VALUES ('DB_CLASS_HIDABLE', 'ABILITY_CLASS') ;
INSERT OR IGNORE INTO TypeTags (Type, Tag)
  SELECT UnitType, 'DB_CLASS_HIDABLE' FROM UNITS WHERE Domain = 'DOMAIN_LAND' AND UnitType NOT IN (
	'UNIT_GIANT_DEATH_ROBOT',
	'UNIT_HELICOPTER',
	'UNIT_DRONE',
	'UNIT_OBSERVATION_BALLOON',
	'UNIT_SPY') ;


INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType) VALUES ('DB_REQ_IS_HIDABLE', 'REQUIREMENT_UNIT_TAG_MATCHES') ;
INSERT OR IGNORE INTO RequirementArguments (RequirementId, Name, Value) VALUES ('DB_REQ_IS_HIDABLE', 'Tag', 'DB_CLASS_HIDABLE') ;
INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES ('DB_REQSET_IS_HIDABLE', 'REQUIREMENTSET_TEST_ALL') ;
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES ('DB_REQSET_IS_HIDABLE', 'DB_REQ_IS_HIDABLE') ;


INSERT INTO GameModifiers (ModifierId) VALUES ('DB_MOD_HIDE_IN_TREES_UNITS_ATTACH_MODIFIER') ;
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES ('DB_MOD_HIDE_IN_TREES_UNITS_ATTACH_MODIFIER', 'MODIFIER_ALL_UNITS_ATTACH_MODIFIER', 'DB_REQSET_IS_HIDABLE') ;
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_MOD_HIDE_IN_TREES_UNITS_ATTACH_MODIFIER', 'ModifierId', 'DB_MOD_HIDE_IN_TREES') ;
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES ('DB_MOD_HIDE_IN_TREES', 'DB_DM_IS_HIDDEN', 'DB_REQSET_HAS_TREES') ;
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_MOD_HIDE_IN_TREES', 'Hidden', 1) ;


INSERT INTO Types (Type, Kind) VALUES ('DB_ABILITY_HIDE_IN_TREES', 'KIND_ABILITY') ; 
INSERT INTO TypeTags (Type, Tag) VALUES ('DB_ABILITY_HIDE_IN_TREES', 'DB_CLASS_HIDABLE') ; 
INSERT INTO UnitAbilities (UnitAbilityType, Name, Description) VALUES ('DB_ABILITY_HIDE_IN_TREES', 'LOC_DB_ABILITY_HIDE_IN_TREES_NAME', 'LOC_DB_ABILITY_HIDE_IN_TREES_DESC') ;


-- Stealth promotions no longer work, so we have to swap them out for something else...
DELETE FROM UnitPromotions WHERE UnitPromotionType IN ('PROMOTION_MONK_TWILIGHT_VEIL', 'PROMOTION_CAMOUFLAGE') ;

INSERT OR IGNORE INTO Types 
(Type,								Kind) VALUES
('DB_PROMOTION_MONK_CHAKRA',		'KIND_PROMOTION'),
('DB_PROMOTION_RECON_SURIVALIST',	'KIND_PROMOTION')
;

INSERT OR IGNORE INTO UnitPromotions
(UnitPromotionType,					Level,	Column,	PromotionClass,				Name,									Description) VALUES
('DB_PROMOTION_MONK_CHAKRA',		1,		3,		'PROMOTION_CLASS_MONK',		'LOC_DB_PROMOTION_CHAKRA_NAME',			'LOC_DB_PROMOTION_CHAKRA_DESCRIPTION'),
('DB_PROMOTION_RECON_SURIVALIST',	4,		2,		'PROMOTION_CLASS_RECON',	'LOC_DB_PROMOTION_SURVIVALIST_NAME',	'LOC_DB_PROMOTION_SURVIVALIST_DESCRIPTION')
;

INSERT OR IGNORE INTO UnitPromotionModifiers
(UnitPromotionType,					ModifierId) VALUES
('DB_PROMOTION_MONK_CHAKRA',		'DB_MOD_+10_HEALING'),
('DB_PROMOTION_RECON_SURIVALIST',	'DB_MOD_HEAL_AFTER_ACTION')
;

DELETE FROM UnitPromotionPrereqs WHERE UnitPromotion IN ('PROMOTION_MONK_TWILIGHT_VEIL', 'PROMOTION_CAMOUFLAGE') ;

INSERT INTO UnitPromotionPrereqs 
(UnitPromotion, 					PrereqUnitPromotion) VALUES
('PROMOTION_MONK_EXPLODING_PALMS', 	'DB_PROMOTION_MONK_CHAKRA'),
('PROMOTION_MONK_DISCIPLES', 		'DB_PROMOTION_MONK_CHAKRA'),
('DB_PROMOTION_RECON_SURIVALIST', 	'PROMOTION_SPYGLASS'),
('DB_PROMOTION_RECON_SURIVALIST', 	'PROMOTION_AMBUSH')
;