UPDATE District_Adjacencies SET YieldChangeId = 'District_Culture_Standard' WHERE YieldChangeId = 'District_Culture' AND DistrictType = 'DISTRICT_THEATER' ;

INSERT OR IGNORE INTO Types (Type, Kind) VALUES ('DB_DM_CITIES_ADJUST_DISTRICT_YIELD_BASED_ON_APPEAL', 'KIND_MODIFIER') ;
INSERT OR IGNORE INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES ('DB_DM_CITIES_ADJUST_DISTRICT_YIELD_BASED_ON_APPEAL', 'COLLECTION_ALL_CITIES', 'EFFECT_ADJUST_DISTRICT_YIELD_BASED_ON_APPEAL') ;

INSERT OR IGNORE INTO GameModifiers (ModifierId) VALUES
('DB_MOD_THEATER_CULTURE_FROM_CHARMING_APPEAL'),
('DB_MOD_THEATER_CULTURE_FROM_BREATHTAKING_APPEAL') ;

INSERT OR IGNORE INTO Modifiers(ModifierId, ModifierType) VALUES
('DB_MOD_THEATER_CULTURE_FROM_CHARMING_APPEAL', 'DB_DM_CITIES_ADJUST_DISTRICT_YIELD_BASED_ON_APPEAL'),
('DB_MOD_THEATER_CULTURE_FROM_BREATHTAKING_APPEAL', 'DB_DM_CITIES_ADJUST_DISTRICT_YIELD_BASED_ON_APPEAL') ;

INSERT OR IGNORE INTO ModifierArguments(ModifierId, Name, Value) VALUES
('DB_MOD_THEATER_CULTURE_FROM_CHARMING_APPEAL', 'Description', 'LOC_DB_MOD_CULTURE_FROM_CHARMING_APPEAL_DESC'),
('DB_MOD_THEATER_CULTURE_FROM_CHARMING_APPEAL', 'DistrictType', 'DISTRICT_THEATER'),
('DB_MOD_THEATER_CULTURE_FROM_CHARMING_APPEAL', 'RequiredAppeal', 2),
('DB_MOD_THEATER_CULTURE_FROM_CHARMING_APPEAL', 'YieldType', 'YIELD_CULTURE'),
('DB_MOD_THEATER_CULTURE_FROM_CHARMING_APPEAL', 'YieldChange', 1),

('DB_MOD_THEATER_CULTURE_FROM_BREATHTAKING_APPEAL', 'Description', 'LOC_DB_MOD_CULTURE_FROM_BREATHTAKING_APPEAL_DESC'),
('DB_MOD_THEATER_CULTURE_FROM_BREATHTAKING_APPEAL', 'DistrictType', 'DISTRICT_THEATER'),
('DB_MOD_THEATER_CULTURE_FROM_BREATHTAKING_APPEAL', 'RequiredAppeal', 4),
('DB_MOD_THEATER_CULTURE_FROM_BREATHTAKING_APPEAL', 'YieldType', 'YIELD_CULTURE'),
('DB_MOD_THEATER_CULTURE_FROM_BREATHTAKING_APPEAL', 'YieldChange', 1)
 ;