DELETE FROM Policies WHERE 
PolicyType = 'POLICY_LAND_SURVEYORS' 
OR PolicyType = 'POLICY_PROFESSIONAL_ARMY' 
OR PolicyType = 'POLICY_RETINUES' 
OR PolicyType = 'POLICY_FORCE_MODERNIZATION' 
OR PolicyType = 'POLICY_EXPROPRIATION' ;

DELETE FROM ObsoletePolicies WHERE 
PolicyType = 'POLICY_LAND_SURVEYORS' 
OR PolicyType = 'POLICY_PROFESSIONAL_ARMY' 
OR PolicyType = 'POLICY_RETINUES' 
OR PolicyType = 'POLICY_FORCE_MODERNIZATION' 
OR PolicyType = 'POLICY_EXPROPRIATION' 

OR ObsoletePolicy = 'POLICY_LAND_SURVEYORS' 
OR ObsoletePolicy = 'POLICY_PROFESSIONAL_ARMY' 
OR ObsoletePolicy = 'POLICY_RETINUES' 
OR ObsoletePolicy = 'POLICY_FORCE_MODERNIZATION' 
OR ObsoletePolicy = 'POLICY_EXPROPRIATION' ;