DELETE FROM Districts WHERE DistrictType = 'DISTRICT_GOVERNMENT' ;
DELETE FROM Buildings WHERE BuildingType IN (
'BUILDING_GOV_TALL',
'BUILDING_GOV_WIDE',
'BUILDING_GOV_CONQUEST',
'BUILDING_GOV_CITYSTATES',
'BUILDING_GOV_SPIES',
'BUILDING_GOV_FAITH',
'BUILDING_GOV_MILITARY',
'BUILDING_GOV_CULTURE',
'BUILDING_GOV_SCIENCE',
'BUILDING_QUEENS_BIBLIOTHEQUE'
) ;

UPDATE Buildings SET AdjacentDistrict = NULL WHERE BuildingType = 'BUILDING_CASA_DE_CONTRATACION' ;