--		Create Courthouse building
INSERT INTO Types (Type, Kind) VALUES ('BUILDING_DB_COURTHOUSE', 'KIND_BUILDING') ;
INSERT INTO Buildings (BuildingType, Name, Description, PrereqDistrict, Cost, PrereqCivic, PurchaseYield) VALUES ('BUILDING_DB_COURTHOUSE', 'LOC_BUILDING_DB_COURTHOUSE', 'LOC_BUILDING_DB_COURTHOUSE_DESC', 'DISTRICT_CITY_CENTER', 150, 'CIVIC_STATE_WORKFORCE', 'YIELD_GOLD') ;
INSERT INTO BuildingPrereqs (Building, PrereqBuilding) VALUES ('BUILDING_DB_COURTHOUSE', 'BUILDING_MONUMENT') ;

INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES ('BUILDING_DB_COURTHOUSE', 'DB_COURTHOUSE_GRANTS_GOVERNOR_TITLE') ;
INSERT INTO Modifiers (ModifierId, ModifierType, Permanent, RunOnce) VALUES ('DB_COURTHOUSE_GRANTS_GOVERNOR_TITLE', 'MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS', 1, 1) ;
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES ('DB_COURTHOUSE_GRANTS_GOVERNOR_TITLE', 'Delta', 1) ;


