UPDATE LocalizedText SET Text = Text || CASE WHEN INSTR(Text, 'GOLD') = 0 THEN '{LOC_GOLD_LABEL}' ELSE '' END WHERE Tag = 'LOC_PEDIA_CONCEPTS_PAGEGROUP_SCIENCE_NAME' AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = Text || CASE WHEN INSTR(Text, 'GOLD') = 0 THEN '{LOC_GOLD_LABEL}' ELSE '' END WHERE Tag = 'LOC_PEDIA_CONCEPTS_PAGE_SCIENCE_2_CHAPTER_CONTENT_TITLE' AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = Text || CASE WHEN INSTR(Text, 'GOLD') = 0 THEN '{LOC_GOLD_LABEL}' ELSE '' END WHERE Tag = 'LOC_PEDIA_CONCEPTS_PAGEGROUP_CULTURE_NAME' AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = Text || CASE WHEN INSTR(Text, 'GOLD') = 0 THEN '{LOC_GOLD_LABEL}' ELSE '' END WHERE Tag = 'LOC_PEDIA_CONCEPTS_PAGE_CULTURE_2_CHAPTER_CONTENT_TITLE' AND Language = 'en_US' ;

-- ('', '', 'en_US'),

INSERT OR IGNORE INTO LocalizedText 
(Tag, Text, Language) VALUES
('LOC_PEDIA_CONCEPTS_PAGE_SCIENCE_2_CHAPTER_CONTENT_PARA_2', '{LOC_DB_LEARN_FROM_OTHER_CIVS_EXPLANATION}' , 'en_US'),
('LOC_PEDIA_CONCEPTS_PAGE_CULTURE_2_CHAPTER_CONTENT_PARA_2', '{LOC_DB_LEARN_FROM_OTHER_CIVS_EXPLANATION}' , 'en_US') ;
