DELETE FROM GoodyHutSubTypes WHERE SubTypeGoodyHut IN (
'GOODYHUT_TWO_CIVIC_BOOSTS', 
'GOODYHUT_MEDIUM_GOLD', 
'GOODYHUT_SMALL_GOLD', 
'GOODYHUT_MEDIUM_FAITH', 
'GOODYHUT_SMALL_FAITH', 
'GOODYHUT_GRANT_UPGRADE', 
'GOODYHUT_HEAL', 
'GOODYHUT_ONE_TECH', 
'GOODYHUT_TWO_TECH_BOOSTS', 
'GOODYHUT_GRANT_SETTLER', 
'GOODYHUT_GOVERNOR_TITLE', 
'GOODYHUT_RESOURCES',
'GOODYHUT_GRANT_SCOUT'

/*	these are the ones we do want (keeping them here in commented-out form in case we want to test goody huts in the future)
,'GOODYHUT_ADD_POP'
,'GOODYHUT_GRANT_BUILDER'
,'GOODYHUT_GRANT_EXPERIENCE'
,'GOODYHUT_GRANT_TRADER'
,'GOODYHUT_LARGE_GOLD'
,'GOODYHUT_ONE_CIVIC_BOOST'
,'GOODYHUT_ONE_RELIC'
,'GOODYHUT_ONE_TECH_BOOST'
*/

) ;


UPDATE GoodyHutSubTypes SET Turn = 0, Weight = 100, RequiresUnit = 0, GoodyHut = 'GOODYHUT_MILITARY' WHERE GoodyHut != 'METEOR_GOODIES' ;
DELETE FROM GoodyHuts WHERE GoodyHutType NOT IN ('GOODYHUT_MILITARY', 'METEOR_GOODIES') ;
UPDATE GoodyHutSubTypes SET RequiresUnit = 1 WHERE SubTypeGoodyHut = 'GOODYHUT_GRANT_EXPERIENCE' ;
UPDATE ModifierArguments SET Value = 999 WHERE ModifierId = 'GOODY_MILITARY_GRANT_EXPERIENCE' AND Name = 'Amount' ;

INSERT INTO GoodyHutSubTypes (GoodyHut, SubTypeGoodyHut, Description, ModifierID, MinOneCity, Weight) VALUES
/*	these don't work...
	('GOODYHUT_MILITARY', 'DB_GOODY_ANTI_CAV', 'LOC_DB_GOODY_ANTI_CAV', 'DB_MOD_GRANT_ANTI_CAV', 1, 100),
	('GOODYHUT_MILITARY', 'DB_GOODY_HEAVY_CAV', 'LOC_DB_GOODY_HEAVY_CAV', 'DB_MOD_GRANT_HEAVY_CAV', 1, 100),
	('GOODYHUT_MILITARY', 'DB_GOODY_LIGHT_CAV', 'LOC_DB_GOODY_LIGHT_CAV', 'DB_MOD_GRANT_LIGHT_CAV', 1, 100),
	('GOODYHUT_MILITARY', 'DB_GOODY_RECON', 'LOC_DB_GOODY_RECON', 'DB_MOD_GRANT_RECON', 1, 100),
	('GOODYHUT_MILITARY', 'DB_GOODY_SIEGE', 'LOC_DB_GOODY_SIEGE', 'DB_MOD_GRANT_SIEGE', 1, 100),
*/

	('GOODYHUT_MILITARY', 'DB_GOODY_MELEE', 'LOC_DB_GOODY_MELEE', 'DB_MOD_GRANT_MELEE', 1, 100),
	('GOODYHUT_MILITARY', 'DB_GOODY_RANGED', 'LOC_DB_GOODY_RANGED', 'DB_MOD_GRANT_RANGED', 1, 100)
;

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent) VALUES
/*
	('DB_MOD_GRANT_ANTI_CAV', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1),
	('DB_MOD_GRANT_HEAVY_CAV', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1),
	('DB_MOD_GRANT_LIGHT_CAV', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1),
	('DB_MOD_GRANT_RECON', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1),
	('DB_MOD_GRANT_SIEGE', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1),
*/
	('DB_MOD_GRANT_MELEE', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1),
	('DB_MOD_GRANT_RANGED', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1)
;

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
/*
	('DB_MOD_GRANT_ANTI_CAV', 'UnitPromotionClassType', 'PROMOTION_CLASS_ANTI_CAVALRY'),
	('DB_MOD_GRANT_HEAVY_CAV', 'UnitPromotionClassType', 'PROMOTION_CLASS_HEAVY_CAVALRY'),
	('DB_MOD_GRANT_LIGHT_CAV', 'UnitPromotionClassType', 'PROMOTION_CLASS_LIGHT_CAVALRY'),
	('DB_MOD_GRANT_RECON', 'UnitPromotionClassType', 'PROMOTION_CLASS_RECON'),
	('DB_MOD_GRANT_SIEGE', 'UnitPromotionClassType', 'PROMOTION_CLASS_SIEGE'),
*/
	('DB_MOD_GRANT_MELEE', 'UnitPromotionClassType', 'PROMOTION_CLASS_MELEE'),
	('DB_MOD_GRANT_RANGED', 'UnitPromotionClassType', 'PROMOTION_CLASS_RANGED')
;

